### ISSUE TITLE
Text shadows

### ISSUE THREAD

**Issue by amyjko** [wordplaydev/wordplay#130]
It would be nice to support text shadows in Phrases, providing granular control over the offset, blur, and color. Putting these in poses and then tweening them would allow for some cool animations.

Here's the CSS documentation for `text-shadow`:

https://developer.mozilla.org/en-US/docs/Web/CSS/text-shadow

The design would likely involve adding three properties to Pose to capture offset, color, and blur.

**Comment by Atesfahun** [comment]
Hi there!

I'd like to take on this task.

**Comment by KG0797** [comment]
Hi,
Ok! I’m working on the theme issue recently.

Best,
Katherine

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: abbyyT ***@***.***>
发送时间: Wednesday, October 25, 2023 10:44:53 AM
收件人: wordplaydev/wordplay ***@***.***>
抄送: Katherine Guo ***@***.***>; Assign ***@***.***>
主题: Re: [wordplaydev/wordplay] Text shadows (Issue #130)


Hi there!

I'd like to take on this task.

―

**Comment by amyjko** [comment]
@Atesfahun, it looks like there are four other folks already assigned to this, @KG0797 included? All, please chime in on who owns this, and what the status is, so @Atesfahun knows if there's room to contribute.

**Comment by marinawooden** [comment]
Hello - me and @mayreene and @andrea-dan are about half way done with this and have been working on it for ~3 weeks now.  We are doing fine right now, but if there are no other issues to take care of we'd be fine with another person too

**Comment by amyjko** [comment]
Hi @marinawooden, @KG0797, @andrea-dan, and @mayrenne,

It's the end of the quarter, so please post an update on this issue. Things to consider:

* Should you still be the assignee? (If you're planning on working on it, yes! Submit a comment explaining your plans. If not, then unassign yourself, so others are eligible to grab it).
* Do you have any work products that are hosted outside of GitHub? Embed them in this issue, so others can build off of them.
* Are there any branches associated with this issue? Please link to them in the issue.

If there's nothing to change above, then at least post a comment indicating that you've seen this. Thanks!

**Comment by marinawooden** [comment]
We have implemented the text shadows feature and it is recognized by the language, however before considering this issue as complete, we'd like to finish implementing the palette editor.  I plan to work on this issue over the next few weeks, and if it is still not resolved then I will continue working on it during winter quarter.  I cannot speak for @andrea-dan and @mayrenne's plans.

**Comment by amyjko** [comment]
Sounds good! Let me know if you get stuck, I'm here to help.

**Comment by marinawooden** [comment]
I am unfortunately unable to continue working on this project due to some scheduling issues with classes.  All current work done on this issue has been pushed up.

Currently, there is an `Aura` api on `Phrase` which takes some properties `offsetX`, `offsetY`, `color` and `blur`, and is recognized by the language.  The last step for this would be to create an option in the palette editor to visual update these attributes.

Example usage of `Aura`:
```
Phrase("Hello World", Aura(offsetX:5, offsetY:5, blur: 5, color:Color(...)))
```
For anybody who picks up this issue and would like to talk to me more about the implementation, my email is [mwoode@uw.edu](mailto:mwoode@uw.edu)

**Comment by amyjko** [comment]
Thank you for the update @marinawooden! @andrea-dan, I see you're still assigned. Are you able to finalize the pull request for this so we can release the feature? If not, please comment and let us know, so we can find someone else to finish the work.

**Comment by amyjko** [comment]
@andrea-dan, just checking in again on my comment above.

**Comment by amyjko** [comment]
No reply from @andrea-dan, removing from issue. Since no one has picked this up, I'll finish it.
