### ISSUE TITLE
Mexican Spanish

### ISSUE THREAD

**Issue by amyjko** [wordplaydev/wordplay#139]
**What's the problem?**
We need a Mexican Spanish locale.

**Who benefits?**
All fluent Spanish readers; 10% of the world.

**Comment by amyjko** [comment]
The app is done, the tutorial remains!

@cmdharo There are other contributors to this. They should be added as assignees to this issue.

**Comment by amyjko** [comment]
Hi @cmdharo,

It's the end of the quarter, so please post an update on this issue. Things to consider:

* Should you still be the assignee? (If you're planning on working on it, yes! Submit a comment explaining your plans. If not, then unassign yourself, so others are eligible to grab it).
* Do you have any work products that are hosted outside of GitHub? Embed them in this issue, so others can build off of them.
* Are there any branches associated with this issue? Please link to them in the issue.

If there's nothing to change above, then at least post a comment indicating that you've seen this. Thanks!

**Comment by cmdharo** [comment]
Hello @amyjko , yes!

Immediate plans:
- Ensure no untranslated strings in the tutorial
- Double-check that programming is being translated in the tutorial.

Future plans (might be better to open new issues):
- Update any missing/outdated strings in es-MX.json when they appear.
- Review the tutorial for clarity, mistranslations, and consistency.
- Run tutorial through more Spanish speakers for input!!

**Comment by amyjko** [comment]
Great! For this issue, you could either 1) close it and open new issues for the remaining work, or 2) leave it open as a broad representation of the work above. The benefit of smaller issues is that we can assign specific people to smaller scopes of work, and more easily keep track of the work. But with that comes the work of specifying the work to be done :)
