### ISSUE TITLE
Arrow keys to modify numeric text fields

### ISSUE THREAD

**Issue by amyjko** [wordplaydev/wordplay#176]
## What's the problem?

There are many text fields in the palette that represent numbers (e.g., `offset` or `place` on `Phrase`). Editing them by typing is a bit slow and error prone (changing `9` to `10` requires deleting `10` then typing `9`).

## What's the idea?

Handle arrow up and down within the text field to increment and decrement numeric values, for quick adjustments. The example above would be achieved by just pressing the down arrow to decrement 10 to 9.

## Who benefits?

Anyone using the palette to tweak a design.

## Design ideas

I think simple keyboard shortcuts on the field for up and down would suffice.

**Comment by wkxdavid** [comment]
@amyjko 
Unless I am misunderstanding the issue, I believe the ability to use arrow key navigability for numeric values is working as its in a arrow key navigability slider. Can I get clarification on this?

**Comment by amyjko** [comment]
@wkxdavid This issue refers to text fields, not sliders. I updated the description with a more concrete example of this.

**Comment by shiinasugioka** [comment]
[Pull request](https://github.com/wordplaydev/wordplay/pull/323)

**Comment by amyjko** [comment]
Hi @shiinasugioka and @wkxdavid! Please address the pull request feedback on this issue (including citing this issue in a commit with the text "Fixed #176" so that they are linked.

**Comment by shiinasugioka** [comment]
Hi Amy! I'm going to remove myself from this issue and leave notes for the next person to take a look at. If anyone working on this issue has any questions, feel free to message me on discord (@ Shiina#3331 )

**Comment by amyjko** [comment]
@shiinasugioka, you're not going to finish this pull request then? @wkxdavid, are you going to finish it? If not, you should unassign yourself from the pull request as well, so everyone knows that you're not going to finish it.

**Comment by shiinasugioka** [comment]
@amyjko Actually, sorry I will finish it. I misread the PR comments and thought I had to redo a lot more than I actually had to. I’m not signed up for Wordplay so I thought this would be a good starter issue for a new dev, but looks like I just commit a bunch of file changes that I shouldn’t have. I can get it fixed by the end of the week and I’ll update my PR!

**Comment by amyjko** [comment]
Thanks @shiinasugioka. Let me know if you have any questions; I'll review your revised PR when it's ready.
