### ISSUE TITLE
Show progress on moderation page

### ISSUE THREAD

**Issue by amyjko** [wordplaydev/wordplay#191]
## What's the problem?

When a moderator is moderating projects, there's no way to know how many more there are.

## What's the idea?

Show some kind of remaining number of projects.

## Who benefits?

Moderators, who may get fatigued, and may benefit from knowing how many are left.

## Design ideas

The paginated query in `/moderate/+page.svelte` should be able to return a length, and then we can render a progress counter.

**Comment by amyjko** [comment]
Hi @andrewle7!

It's the end of the quarter, so please post an update on this issue. Things to consider:

* Should you still be the assignee? (If you're planning on working on it, yes! Submit a comment explaining your plans. If not, then unassign yourself, so others are eligible to grab it).
* Do you have any work products that are hosted outside of GitHub? Embed them in this issue, so others can build off of them.
* Are there any branches associated with this issue? Please link to them in the issue.

If there's nothing to change above, then at least post a comment indicating that you've seen this. Thanks!

**Comment by andrewle7** [comment]
in the testing phase, will push final product today. got a counter, but still testing cases (skips, and behavior of counter for that) mostly done.

**Comment by amyjko** [comment]
I look forward to it! Expect feedback and iteration; I always find a few things to fix in a PR.
