### ISSUE TITLE
Documentation for Automated Testing

### ISSUE THREAD

**Issue by wudel22** [wordplaydev/wordplay#194]
@amyjko 
## What's the problem?

What are you trying to do? Is there a problem you're encountering or a wish you have?
- Some members of the testing/verification group are interested or wondering about how automated testing works. Where can they do it, how do they do it, and a description of automated testing so they know what it is and how it will work. 

## What's the idea?

How would we address the problem with a new or changed feature?
- We will need a documentation for automated testing on or linked to the verification wiki for easy access. As mentioned above, we would like a brief explanation on what automated testing is, if there are any new technologies we need to download for doing automated testing, where can we do automated testing, how to do automated testing (assuming there are members who are just interested in testing and don't have any experience with it), as well as how to use/run automated testing

## Who benefits?

Is this something you think only you would benefit from? Are there others that would benefit? Are there others that might be harmed by supporting this?
- This will benefit everyone on the testing/verification team because we don't want to manually test things every time there is a new update, so learning about automated testing will be a huge benefit to everyone on board.

## Design ideas

A clear and concise description of designs you've considered. If you don't have a concrete idea, that's okay. We'll revise this issue with designs later.
- I mentioned this previously that we would like a fairly detailed documentation about what automated testing is, if there are external or internal software downloads that are needed, where to write these automated tests, how to write automated tests (can be a linked video to teach the testers), how to run automated tests and use them, as well as any form of important information about wordplay specifically portions that already has automated tests to set an example.

**Comment by amyjko** [comment]
Thanks @wudel22! I reviewed the `verify` wiki to look for gaps between what was there and what you requested. The only thing really missing was a link to an example tutorial on automated testing and vitest, so I just added links to those. All of those tutorials will answer all of the questions you noted above. (And there are thousands more online you can find).

If there's something you think is missing from the wiki page, or from the many tutorials online about the topic, or from the hundreds of test examples in `src`, let me know, and I can write to fill in the gaps. Remember: this is an independent study, so I expect you'll go find learning materials, teach yourselves together, and let me know when the materials online aren't enough to get you unstuck.
