### ISSUE TITLE
unable to log in on edge or google chrome

### ISSUE THREAD

**Issue by willGG11** [wordplaydev/wordplay#202]
## Expected behavior
expected to log in on Wordplay Web as type in an email address

## Actual behavior
receives "unable to log in prompt". And no email link was sent for logging in

Provide detailed steps that consistently reproduce the behavior, including any example code. If you can, make the steps as minimal as possible, finding the smallest possible set of steps that still produce the unexpected behavior.

1. Go to 'https://test.wordplay.dev/'
2. Click on 'login'
3. Type in email address
4. press the login button
5. receives "unable to log in prompt :("

## Screenshots

<img width="1125" alt="截屏2023-10-14 16 16 08" src="https://github.com/wordplaydev/wordplay/assets/106497657/10bdd036-fc05-4eda-80cc-da158e3ae9c0">

## Environment

What platform, OS, browser, and version are you using? Please be exact with version numbers, as different versions can result in a defect happening or not.

Desktop

-   OS: v.12.4
-   Browser Chrome 
-  Version: 117.0.5938.149
- Browser Edge
- Version: 118.0.2088.46
-------------------
the errors prompts:
Failed to load resource: the server responded with a status of 400 ()
FirebaseError: Installations: Create Installation request failed with error "400 INVALID_ARGUMENT: API key not valid. Please pass a valid API key." (installations/request-failed).
    at DC (stores.9c84ff7c.js:3212:240)
    at async bU (stores.9c84ff7c.js:3227:481)
    at async DU (stores.9c84ff7c.js:3332:740)
localhost:9099/ident…eymyfakeapikeymyf:1 
 
 Failed to load resource: net::ERR_CONNECTION_REFUSED
9.17f40056.js:1 
 auth/network-request-failed
9.17f40056.js:1 
 Firebase: Error (auth/network-request-failed).

**Comment by amyjko** [comment]
Clarification: are you running locally the Firebase emulator (`npm run emu`) when you're doing this? If not, this is expected behavior, since there's no authentication backend. If you _are_ running the emulator, or you're testing on the staging server (`test.wordplay.dev`), then this is a defect.

**Comment by willGG11** [comment]
Confirmed: use both "test.wordplay.dev" and  Firebase emulator( localhost:5173) to login and receive failed prompt

**Comment by willGG11** [comment]
> Clarification: are you running locally the Firebase emulator (`npm run emu`) when you're doing this? If not, this is expected behavior, since there's no authentication backend. If you _are_ running the emulator, or you're testing on the staging server (`test.wordplay.dev`), then this is a defect.

Confirmed: use both "test.wordplay.dev" and Firebase emulator( localhost:5173) to login and receive failed prompt

**Comment by amyjko** [comment]
Can you edit your OS information above? You specified a version but not an operating system.

**Comment by amyjko** [comment]
(Note: running the Vite dev sever is not the same as running the Firebase emulator. To run the emulator, you have to explicitly run the command `npm run emu`).

**Comment by amyjko** [comment]
Tested with emulator and on [https://test.wordplay.dev](https://test.wordplay.dev); cannot reproduce. Please provide your OS information and any information in the browser inspector console.

**Comment by willGG11** [comment]
I think we can close the issue just for now because I can not reproduce the issue either. I don't now the reason that cause the issue. I believe it might be the unstable internet connection from my end...

**Comment by willGG11** [comment]
> (Note: running the Vite dev server on localhost is not the same as running the Firebase emulator. To run the emulator, you have to explicitly run the command `npm run emu`).

I ran the npm run emu command yesterday. it is weird that it didn't let me log in nither. I tried today and it works as normal.  I guess it is the issue from my end and not a bug though.

**Comment by amyjko** [comment]
Thanks for reporting @willGG11! Issues like this that depend on backend authentication infrastructure are always hard to test.

**Comment by amyjko** [comment]
I believe I

**Comment by willGG11** [comment]
confirmed: it is working now! :>

**Comment by amyjko** [comment]
Wonderful, thanks for confirming, and reporting.
