### ISSUE TITLE
Explain beta

### ISSUE THREAD

**Issue by amyjko** [wordplaydev/wordplay#203]
## What's the problem?

When visitors reach the landing page, the only signal that the site is beta is the small label at the bottom. We need a much stronger set of expectation setting, so that people don't expect everything to work, and help report issues.

## What's the idea?

Perhaps a special paragraph at the top that goes to the milestone page.

## Who benefits?

Every visitor. 

## Design ideas

TBD

**Comment by amyjko** [comment]
@kelliannr, I see you added yourself to this. Did you want to work on this? I was just going to add some text to the landing page.

**Comment by amyjko** [comment]
Remember, if someone is already assigned an issue, you need to explicitly coordinate with them, otherwise they don't know that you're also working on it. Explicit communication is essential to avoiding conflicts and redundant work. For example, I was planning on working on this issue this morning, but now I don't know if I should, because maybe you're working on it too? Please communicate your plans.

**Comment by kelliannr** [comment]
Hello, sorry for the late reply! Me and Megan started working on this on Tuesday and were putting together a design to show you for approval. Here is what we have so far:
<img width="487" alt="Screenshot 2023-10-19 at 10 19 02 AM" src="https://github.com/wordplaydev/wordplay/assets/73355041/f32e119d-2891-4b30-bacf-59936f61272e">

Not fully fleshed out yet, but thats what we have

**Comment by amyjko** [comment]
I like the visual design! A few notes:

* It should use the existing color palette defined in `global.css`, rather than using any new hard coded colors
* I think the message needs to be tweaked a bit, to include a link to where to report issues. (The current beta link in the footer goes there, but that will be less discoverable).
* What about just replacing function's speech bubble text with the beta text? That takes up less space, and is more prominent.
* This needs to be localized, so you'll need to coordinate with the Chinese and Spanish team for translations.

This must be built ASAP, since we release in 11 days. I can do it quickly, or you could find a developer who wants to take it on and is willing to do it quickly. Your choice (but at some point, given the urgency, I will be the fallback dev to build it).

**Comment by amyjko** [comment]
I think I'll work on building this this weekend, using your sketch as a guide, but leave in localization placeholders. Can you coordinate with localization to craft text for this, and I'll build and finalize English text?

**Comment by kelliannr** [comment]
Ok, sounds good. Should I ask them to localize the text present in the sketch or should I direct them to you for specific text?

**Comment by amyjko** [comment]
I'll merge the implementation today, with placeholders for the non-English locales, and so you can just alert them to the placeholders.

**Comment by amyjko** [comment]
Okay, all built, thank you for designing! I've included placeholders for the localization team to translate. Thanks for nudging them.
