### ISSUE TITLE
Drag hover feedback on code examples is clipped in a confusing way

### ISSUE THREAD

**Issue by Marc0Guo** [wordplaydev/wordplay#206]
## Expected behavior

The f repeat box should become larger without any part get hidden

## Actual behavior

Go to learn, go to "the verse-silence-3/15", flick on function. When move the cursor to "f repeat", part of the image was hidden.

## Screenshots

<img width="954" alt="截屏2023-10-17 下午5 40 42" src="https://github.com/wordplaydev/wordplay/assets/146252292/b03c133d-5d44-4eb2-b8da-2fd0bfbaff34">
<img width="977" alt="截屏2023-10-17 下午5 42 07" src="https://github.com/wordplaydev/wordplay/assets/146252292/9ecce814-f198-48f7-a023-cc6f6d9cf64a">

## Environment

What platform, OS, browser, and version are you using? Please be exact with version numbers, as different versions can result in a defect happening or not.

Desktop

-   Device: macbook pro, intel chip
-   OS: macOS 12.6.6
-   Browser: Firefox
-   Version: 118.0.1

**Comment by amyjko** [comment]
Clarification: the details above says you were running this on Firefox on iOS? Were you using an iPhone or iPad?

**Comment by amyjko** [comment]
This is by design: hovering over code that is draggable scales it a small amount to indicate that it is draggable. So this is intended, but confusing.

Redesign considerations: what would be a clearer signal that the code is draggable, instead of scaling it to be larger on hover?

**Comment by Marc0Guo** [comment]
I'm using a mac

**Comment by amyjko** [comment]
@Marc0Guo You'll need to be much more precise about your OS and version. Saying "Mac" doesn't specify which OS or which browser version you're using. These things matter, because they change rendering behavior.

**Comment by Marc0Guo** [comment]
Thanks for the clarification. I fixed the OS and version.

**Comment by amyjko** [comment]
Thanks @Marc0Guo! Did you have thoughts about the redesign considerations I noted above? (Since you reported, you're in the best position to talk about design alternatives that might have prevented confusion). Thanks!

**Comment by Marc0Guo** [comment]
Maybe it could have better signal if the user moves cursor on codes, the cursor turns into a hand like this 
![image](https://github.com/wordplaydev/wordplay/assets/146252292/8dcd45c7-876d-4b68-875f-2dba03e9e62e)

**Comment by amyjko** [comment]
I like that; I think it's a simple and effective change. We just need a `cursor: grab;` on the draggable view. I can implement this very quickly, so I'll assign myself as dev and get this fixed.
