### ISSUE TITLE
No connection issue

### ISSUE THREAD

**Issue by Marc0Guo** [wordplaydev/wordplay#207]
## Expected behavior

There should be some features that coming out.

## Actual behavior

When go to gallery, go to tools and click on the three dots. It's showing me the below image. I checked my connection by clicking on other features. Everything works fine.

## Screenshots
<img width="1439" alt="截屏2023-10-17 下午6 00 31" src="https://github.com/wordplaydev/wordplay/assets/146252292/100dc903-c50e-4813-a101-9cab4a42c9ae">
<img width="1440" alt="截屏2023-10-17 下午6 02 46" src="https://github.com/wordplaydev/wordplay/assets/146252292/cf62bd34-1b2f-41b2-bb2f-2494169effc0">

## Environment

Desktop

-   Device: macbook pro, intel chip
-   OS: macOS 12.6.6
-   Browser: Firefox
-   Version: 118.0.1

**Comment by amyjko** [comment]
This is expected behavior for any program that uses the `Webpage` stream and does not have a back end running. Are you running the Firebase emulator (`npm run emu`)? Are you running on `test.wordplay.dev`?

**Comment by Marc0Guo** [comment]
I'm using npm run dev to run on my terminal.

**Comment by amyjko** [comment]
Your reply didn't answer my question. Are you running the emulator? If not, this is expected behavior.

Also, please fix your browser and OS version details. "iOS" is incorrect and you haven't specified any versions.

**Comment by Marc0Guo** [comment]
I'm so sorry, I didn't understand your question. The problem is that I didn't run the back end, so it should be an expected behavior.

**Comment by amyjko** [comment]
Okay, thanks for confirming! (Talking about bugs always requires precise language, which can make it hard to report and triage. You're doing great, keep up the reporting!)
