### ISSUE TITLE
Increment/decrement buttons obscure text

### ISSUE THREAD

**Issue by keki030215** [wordplaydev/wordplay#209]
## Expected behavior

Expected to see no other symbols cover up the original statement.

## Actual behavior

1. Go to 'Project', click it to start 
2. Get to sessions 'It's the little things - Numbers', 'Cast party - Convert', 'Cast party - Decisions', and 'Scene change - Volume'.
3. There will be symbols that covers up the expected statement. (examples in screenshots)

## Screenshots

<img width="388" alt="Screenshot 2023-10-17 at 18 11 35" src="https://github.com/wordplaydev/wordplay/assets/121984396/b1ac3ee0-5a90-4c55-b029-fc703431f6ba">
<img width="463" alt="Screenshot 2023-10-17 at 18 08 02" src="https://github.com/wordplaydev/wordplay/assets/121984396/2ad8fb5a-e898-46e1-8197-1325ca249f3d">

## Environment

-   Device: [MacBook Air M1 chip]
-   OS: [MacOS 13.1]
-   Browser [FireFox]
-   Version [118.0.2]

### Proposal:
A simple fix to just shift everything else in the program over when the number is clicked on:

![Plus and minus increment signs are in their own space and are not obstructed by any other scripts, everything else is shifted right.](https://github.com/wordplaydev/wordplay/assets/114948317/ceacd15e-70b5-409e-bf5e-8a9b1be3d06f)

### Compliance with current design:

This design/behavior is still consistent with the general Wordplay website; there are many instances where scripts in the program expand and shift things over:

![Two lines of the same syntactic code, but the second one is longer because an icon was clicked.](https://github.com/wordplaydev/wordplay/assets/114948317/823f1015-e92e-4658-a2b8-91137aa8d64f)

These two scripts have not been modified; the script expands when pressing on the speech bubble icon.

#### Video link:
[LINK](https://drive.google.com/file/d/1xP2RMuUdpQB2WoWFxFqnvAGrrpPLwfyp/view?usp=sharing)
Demonstrates the current state, proposed/desired state, and example of it existing in the current Wordplay website:

#### Figma prototype of desired state:
Use Flow 1 and turn on “Fit Width” in options for optimal view.
[LINK](https://www.figma.com/proto/YgduZf5H5fw4Lc5JAhrYvI/Design?type=design&node-id=3-1769&t=bhBQ36XVETPLrFaI-1&scaling=scale-down-width&page-id=0%3A1&starting-point-node-id=3%3A1769&mode=design)

**Comment by amyjko** [comment]
Thanks for reporting! This issue needs some redesign before we can fix it.

**Comment by brightuw** [comment]
Requesting to be assigned to this issue!

**Comment by amyjko** [comment]
Go ahead and assign yourself; post here and indicate whether you'll be doing design, dev, or both (both are very much needed, so if you're only doing one, find a collaborator).

**Comment by brightuw** [comment]
Ok, thank you! For future reference, should I just self-assign myself issues? I read on the design w that "One you've chosen an issue that you'd like to own, comment on it, requesting to be assigned. Amy will assign." I just don't want to step on any toes, thank you again.

**Comment by brightuw** [comment]
Working as a designer; in search of a development collaborator.

**Comment by amyjko** [comment]
@brightuw Thanks for reading those instructions closely :) Our practice has drifted away from that guideline (which tells me many others haven't been reading it), but I think this drift is okay. I can't be a bottleneck on all of the issue assignments.

**Comment by amyjko** [comment]
(Documenting Discord discussion with @brightuw: moving this to 1.0 milestone, and @brightuw will act as both designer an developer).

**Comment by brightuw** [comment]
@amyjko Requesting a design review to move into the development stage.

**Comment by amyjko** [comment]
Thanks @brightuw! A few comments:

* Can you convert your PDF to GitHub markdown and embed it in the issue? We don't use PDFs here, they're not screen readable by default, so people who rely on them can't see what's in your design.
* The design proposal is indeed in line with the existing conventions, though I think the existing conventions can feel a bit "jumpy", so I'm not totally happy with them. Let's try it, but keep the size super tight so that jumpiness is minimal.

**Comment by amyjko** [comment]
@brightuw I'm going to try to build this tonight.

**Comment by amyjko** [comment]
@brightuw Are you working on this? It seems like you were going to be developer for this, but I this issue has been silent for a few weeks, and I don't see a branch on this.

**Comment by brightuw** [comment]
Hey, @amyjko. I've still been trying to learn the development outline and architecture but I haven't made much progress. I think for efficient sakes, I think it's best a developer that is more familiar build this instead.

**Comment by amyjko** [comment]
Thanks for the update @brightuw. I'm definitely happy to help you learn this! It's a great focused opportunity to practice many aspects of interaction design and development. But if you don't want to, that's fine, and someone else can tackle it.

**Comment by brightuw** [comment]
Thanks, @amyjko. I'm still interested in attempting to develop this. I will try and communicate my learning and development progress and any issues or obstacles I'm having!

**Comment by amyjko** [comment]
Great! I'm here to help, whatever you need.

**Comment by amyjko** [comment]
Hi @brightuw!

It's the end of the quarter, so please post an update on this issue. Things to consider:

* Should you still be the assignee? (If you're planning on working on it, yes! Submit a comment explaining your plans. If not, then unassign yourself, so others are eligible to grab it).
* Do you have any work products that are hosted outside of GitHub? Embed them in this issue, so others can build off of them.
* Are there any branches associated with this issue? Please link to them in the issue.

If there's nothing to change above, then at least post a comment indicating that you've seen this. Thanks!
