### ISSUE TITLE
Finish Adventure example

### ISSUE THREAD

**Issue by MichelleGuan1128** [wordplaydev/wordplay#213]
## Expected behavior

Expect to see a winning result when clicking on one of the opinions presented in the game.

## Actual behavior

Provide detailed steps that consistently reproduce the behavior, including any example code. If you can, make the steps as minimal as possible, finding the smallest possible set of steps that still produce the unexpected behavior.

1. Go to 'Galleries'.
2. Click on the first game under 'Games'.
3. This game does not have a defined winning endpoint.

## Screenshots

<img width="1395" alt="Screenshot 2023-10-20 at 11 28 13 PM" src="https://github.com/wordplaydev/wordplay/assets/76934364/5fe7a8ef-19bb-4f24-a5db-d5162d2b438b">
<img width="1395" alt="Screenshot 2023-10-20 at 11 28 59 PM" src="https://github.com/wordplaydev/wordplay/assets/76934364/3f1d6d0a-4e6b-4e54-b17b-50b6531ce16d">

In the game, there are two opinions presented, but both choices lead to the same outcome.

## Environment

Device: MacBook Pro Intel Core i5
OS: MacOS 14.0
Browser FireFox
Version 118.0.2

**Comment by amyjko** [comment]
I'll fix this one!
