### ISSUE TITLE
Make it easier to select a single locale

### ISSUE THREAD

**Issue by huangzi11** [wordplaydev/wordplay#215]
## What's the problem?

The problem is related to the language selection feature on the code-learning website. Currently, when a user selects a language, it adds the selected language to the list of available languages, potentially resulting in multiple languages being selected simultaneously. This can be confusing for users as they may not be sure which language will be the primary one. The issue is that the current design lacks clarity and consistency in language selection.

## What's the idea?

To address this problem, the idea is to modify the language selection feature. Users should be able to select only one language at a time. If no language is selected or if a selection is removed, the default language of the website should be English. This change will make the language selection process more straightforward and avoid confusion caused by multiple languages being selected at once.

## Who benefits?

Users: Users will benefit from this change as it simplifies the language selection process, making it more user-friendly and less confusing.

Developers: Developers can benefit from a more straightforward language selection feature, which can lead to a reduction in support requests related to language settings.

## Design ideas

A simple language selection interface that allows users to choose one language from a dropdown list or a set of radio buttons. The default language should be clearly indicated. Additionally, a reset option to set the language back to the default (English) could be included. The design should aim to be intuitive and user-friendly.

**Comment by amyjko** [comment]
I actually just addressed this today, can you pull the change and review my design revision? I made single selection the default and multiple selection possible via a separate button. (Multiple selection is very important to preserve, so and multiple selection in drop downs are not accessible to screen readers).

**Comment by huangzi11** [comment]
I just tried on updated language selection feature, it's making sense and is more accessible for people who are new to this!

**Comment by amyjko** [comment]
Great! If you see other improvements, you can note them here and we can keep this issue open. Otherwise, go ahead and close it if you think it's resolved.

**Comment by amyjko** [comment]
Closing this, but reopen if you have more feedback.
