### ISSUE TITLE
Better feedback on read only projects

### ISSUE THREAD

**Issue by amyjko** [wordplaydev/wordplay#216]
## What's the problem?

When trying to type in a read only project, the cursor shakes, and the screen reader speaks, but it's not clear how to make the project editable. We need to somehow teach the creator that they can copy the project to edit it.

## Problem Statement

How can we provide clear guidance to users to allow them to copy the projects for editing while minimizing confusion and ensuring accessibility?

## User Needs and Flow

1. Needs: I want to edit the read only project 
1. Steps they need to take: User needs to **view** the code of the project first and then **copy** the code to edit it.

## What's the idea?

One way to address this is to pop up a dialog when editing. That's very disruptive, and not particularly accessible.

## Who benefits?

Anyone viewing projects in the gallery, or viewing a public project.

### 1. Change the icon

**Current icon for viewing the code:**
![magnifying glass icon](https://github.com/wordplaydev/wordplay/assets/137957394/f9063ed4-5363-4830-8621-c9d5235d9ab0)
**Problem:** The icon is very confusing as the user is not sure what this icon is referring to. The magnifying glass is commonly used as a representation for the ability to search or zoom. 
**Idea:** Instead of magnifying glass icon, we present “view” icon

![eye icon](https://github.com/wordplaydev/wordplay/assets/137957394/ed5725a5-3308-4adc-8cab-681207054516)
This icon consists of using the “Eye Emoji” unicode character. The Unicode Number, HTML Code, and CSS Code is shown below.

- Unicode Character: (U+1F441)
- HTML Code: "&#128065"
- CSS Code: \1F441

This way, the user can clearly understand that this icon is related to viewing the code. For more information, when the user hover over the icon, the pop up stating “view the code” will show up. This is clearer than the current hover text stating “edit this project,” which can lead users to believe they can edit the code without copying the project first.
![five buttons in a row with a mouse hovering over the second icon, the eye icon. hover text reads "view the code"](https://github.com/wordplaydev/wordplay/assets/137957394/a129cf15-dee2-4eaa-92bf-a8f41731fa0a)

**Current icon for copying the code:**
![pencil next to a plus sign icon](https://github.com/wordplaydev/wordplay/assets/137957394/ed565af9-9028-4963-8c0d-e1cd3ea2017e)

**Problem:** The pencil and the plus sign together are not inherently clear to users what the purpose of the button is. This creates confusion and users may look over this button and not realize that this is how to copy the code.

**Idea:** Instead of the pencil and plus sign, we propose a different “copy” icon
![paper copy next to a plus sign icon](https://github.com/wordplaydev/wordplay/assets/137957394/7a907635-e692-45e5-9434-392339b89067)

This icon consists of using the “Empty Pages” unicode character followed by the “Heavy Plus Sign” unicode character. The Unicode Number, HTML Code, and CSS Code for each of these are shown below.

Empty Pages
- Unicode Number: U+1F5CD
- HTML Code: "&#128461"
- CSS Code: \1F5CD

Heavy Plus Sign
- Unicode Number: U+2795
- HTML Code: "&#10133"
- CSS Code: \2795

With this generic icon that is commonly used for copying in other contexts, the user can understand what this button is for. Additionally, we want to keep the text that says “copy this code” that appears when users hover over the icon.

![mouse hovering over the paper copy next to a plus sign icon, with text reading "copy this code"](https://github.com/wordplaydev/wordplay/assets/137957394/cc774f54-411e-4d9b-966a-bf388865422f)

### 2. Clear Instructions

**Problem:** As of now, there are no written instructions on how to assist users when they are trying to edit the code. 
**Our goal:** Inform the user that they need to view the code and then copy the code to edit them. 
**Idea:** The only idea that came to our mind was the pop up dialog.

**How it works:** When a user opens a project in the galleries and chooses to view the code, a banner with instructions at the bottom of the code appears. This banner will appear right away so the user is informed that if they want to edit the code, they must use the copy button first. Once the user decides they do not want to see this message anymore, they can collapse the message using the arrow button on the right corner of the banner. If they want to read this message, they can expand the banner to its original size using the same arrow button.

Banner (not collapsed) as the user opens the code:
![a screen of a project in galleries with a banner at the bottom instructing to click the copy icon to edit](https://github.com/wordplaydev/wordplay/assets/137957394/7bea7ff6-9297-42cf-961b-d54e83f034df)

Banner collapsed but still available to open and read:
![a screen of a project in galleries with a collapsed banner asking if editing the code is wanted](https://github.com/wordplaydev/wordplay/assets/137957394/11555791-6ee8-4da0-b338-10bc25ee2e10)

**Comment by amyjko** [comment]
Hi @yz425-2036461!

It's the end of the quarter, so please post an update on this issue. Things to consider:

* Should you still be the assignee? (If you're planning on working on it, yes! Submit a comment explaining your plans. If not, then unassign yourself, so others are eligible to grab it).
* Do you have any work products that are hosted outside of GitHub? Embed them in this issue, so others can build off of them.
* Are there any branches associated with this issue? Please link to them in the issue.

If there's nothing to change above, then at least post a comment indicating that you've seen this. Thanks!

**Comment by amyjko** [comment]
No reply, unassigning everyone to free up the issue for others to work on. Reassign yourself if you're still working on it.

**Comment by michelleejkim** [comment]
problems
1. vague icons for "editing and copy this project"
2. when hovering over editing project, the name should be "view code" 
3. when user tries to type, no user feedback -> leading users to be confused on what state they are currently in

solutions
1. change icon for the magnifying glass <edit this project>
4. change icon for the pencil <copy this project>
5. message that tells user that "project has been copied to your own folder. Now, you can edit"
6. after clicking edit icon, message -> "you need to copy the project to edit"

**Comment by michelleejkim** [comment]
view the code -> copy the code -> edit the code

**Comment by amyjko** [comment]
@michelleejkim I'm having trouble interpreting what your comments are. If they are notes to yourself, remember that this is a place for discussion, so you need to explain what you're posting and why others might need the content. If they are a design proposal, those go in the issue body, per the wiki, and you should tag me and ask for review, per the wiki.

**Comment by michelleejkim** [comment]
> @michelleejkim I'm having trouble interpreting what your comments are. If they are notes to yourself, remember that this is a place for discussion, so you need to explain what you're posting and why others might need the content. If they are a design proposal, those go in the issue body, per the wiki, and you should tag me and ask for review, per the wiki.

Sorry about that! These were just notes that Jenny and I discussed. I'll put them into the design proposal after we come up with design solutions and tag you for feedback. Thank you!!

**Comment by amyjko** [comment]
It's the end of Winter! Please provide an update on this issue, including:

* Whether you plan to continue work on it
* If you do not, 1) provide a detailed update of its status, 2) add any unfinished work, 3) list any any unmerged branches, and 4) unassign yourself, so someone else can take over the task. Please leave the issue in better shape than you found it, helping future contributors to start from where you left off.

If you do plan to continue work on it, carry on. Otherwise, thank you for your contributions!

**Comment by amyjko** [comment]
No reply :( Unassigning @jenny-speelmon.

**Comment by jenny-speelmon** [comment]
Hi Amy, I'm sorry about the late reply! Just wanted to update that I will continue working on this issue. For next steps, I would love some feedback on the updated design spec so I know what to change and how to move forward. Thank you for your help!

**Comment by amyjko** [comment]
Thanks @jenny-speelmon! I'm excited you'll continue working on this. Overall, I think the icon and tooltip redesigns are good. One thing to refine, however, is that we've generally avoided using any images for icons, since those impose a higher memory footprint on the platform and require custom image descriptions. Can you identify unicode characters that could capture the spirit of the icon proposals?

Regarding popup and tooltips, the current platform conventions are that popups are only for settings dialogs, since those are more easily designed to be navigable by screenreader. As an alternative, what about a banner on the bottom of the code editor that contains a persistent message about it being read only, and also a button for copying? That would be explicit, visible, navigable, and pretty hard to miss while editing. It could be collapsable if someone wants to get it out of the way and just read. Maybe try that design idea?

**Comment by jenny-speelmon** [comment]
Cammi Pham and I will not be continuing this issue, but this is an update on the progress made! Thank you.

Status: needs feedback on the newly updated design specification.

Details: updated the design to have a banner at the bottom of the screen with instructions to copy the project before editing the code. This banner is open when the user opens the code, so it should be seen immediately. The user can collapse the banner to see the screen better, so a smaller banner replaces it. The user can expand or collapse the banner at any time. Additionally, the newly proposed icons (view and copy) consist of unicode characters rather than images.

**Comment by amyjko** [comment]
Clearing assignees. Thank you for your progress @jenny-speelmon and @cammip.
