### ISSUE TITLE
Vertical right to left layout doesn't make sense for horizontal left-to-right languages

### ISSUE THREAD

**Issue by willGG11** [wordplaydev/wordplay#220]
## What's the problem?

Need to consider a more practical scenario when designing the writing layout feature. 
In our beta version, go to the settings section
and change the writing layout from horizontal to vertical, only making the content flip 90 degrees. Makes users hard to access text. (They had to crane their necks to read the content) and less sense-making.

## What's the design idea?

I think we could optimize the writing layout into reading reading-friendly version.
-----------------------
an example case:
this is a demo (horizontal view)

changing into our new vertical view:

this 
is 
a 
demo
-----------------------
One scenario based on my cultural background:
Chinese have both horizontal and vertical reading and writing habits in different regions
In mainland China, we typically use a horizontal layout:
我喜欢读书
In some regions of China, people prefer a vertical layout, especially in published books:
我
喜
歡
讀
書

It is important to get both layouts accommodated and optimized in the Chinese version of wordplay.
current implementation can't successfully achieve this feature. 
<img width="674" alt="截屏2023-10-23 22 03 52" src="https://github.com/wordplaydev/wordplay/assets/106497657/beb66437-ab46-4e81-8a79-165206206835">
<img width="999" alt="截屏2023-10-23 22 03 24" src="https://github.com/wordplaydev/wordplay/assets/106497657/deae02da-01e6-45c2-9386-f5e08eb2df52">

## Who benefits?

Is this something you think only you would benefit from? Are there others that would benefit? Are there others that might be harmed by supporting this?

Different languages have different reading and writing habits, and this change will benefit people who write and read vertically all over the world. At the same time, it is important to ensure that this change does not affect people who write and read horizontally.

**Comment by amyjko** [comment]
Thanks @willGG11. I'm having a bit of trouble making sense of the design proposal here. Are you proposing that left-to-right, top to bottom languages like English have a vertical reading mode? Or are you proposing to properly support vertical layout for CJK (Chinese/Japanese/Korean) languages?

If the former, yes, we currently provide some unhelpful configurations for Latin scripts, and it might make sense to disallow the ones that don't make sense. If you meant the latter, than this issue should focus on any defects you've found in CJK support.

**Comment by willGG11** [comment]
> Thanks @willGG11. I'm having a bit of trouble making sense of the design proposal here. Are you proposing that left-to-right, top to bottom languages like English have a vertical reading mode? Or are you proposing to properly support vertical layout for CJK (Chinese/Japanese/Korean) languages?
> 
> If the former, yes, we currently provide some unhelpful configurations for Latin scripts, and it might make sense to disallow the ones that don't make sense. If you meant the latter, than this issue should focus on any defects you've found in CJK support.

Right now I am referring to the former issues.  For the latter one, I know we haven't released our beta that supports CJK, it is just a convention.

**Comment by willGG11** [comment]
> Thanks for the clarification! Just to clarify further:
> 
> The current "writing layout" determines whether tex is laid out 1) horizontal left to right, 2) vertical left to right, or 3) vertical right to left. These are the most common layouts for scripts globally. For CJK, option 3 is the default. I think what you're proposing is a fourth thing for option 1 scripts: text that is still laid out horizontal left to right, but with line breaks after each word. Is that your proposal?

I think I am still talking about the second one, sorry for the confusion. I am trying to type in vertical left-to-right format just for an example. But my input source doesn't let me do it :(
I just want to make sure our CJK version will present output like this:

Here is an example of implement Chinsese into vertical left to right formatt.

<img width="216" alt="截屏2023-10-25 21 28 03" src="https://github.com/wordplaydev/wordplay/assets/106497657/3b4066da-cfaf-40fe-8aab-e7cd4a3cce3f">

**Comment by amyjko** [comment]
Ah, sorry for the confusion, "former" means first in the list, "latter" means second. So it sounds like you're specifically talking about CJK vertical right-to-left layout, and you're reporting a defect, not an enhancement. I'm changing the title to reflect the defect you're reporting.

More clarifications:

* Which one of the three writing modes are you choosing in settings that is causing the issue? (I couldn't determine which you selected)
* Which locale have you chosen in the locale chooser? (English, Spanish, Chinese, or some combination)?

The intended behavior is that when you choose Chinese, and you choose vertical right-to-left, it should render correctly. For example, when I choose Chinese, choose vertical right to left in settings, and enter this program:

`Phrase("国际化活动W３Ｃ万维网联盟")`

This is what I see:

<img width="222" alt="image" src="https://github.com/wordplaydev/wordplay/assets/552276/b9effb4a-1d13-4314-9020-f573230681af">

Do you see something different when following these steps?

A few tasks for you:

* Check the reproduction steps I provided above
* If you see something different, change the description above to include the reproduction steps and add exact details of what browser version and operating system version you are using.

If you *do* see what I see, then this is a design issue, as it wasn't clear how to get Chinese text to render as you intended. If that's the case, then we have to do some redesign to make it clearer than the current approach (choose Chinese, change to vertical rtl).

**Comment by willGG11** [comment]
> Ah, sorry for the confusion, "former" means first in the list, "latter" means second. So it sounds like you're specifically talking about CJK vertical right-to-left layout, and you're reporting a defect, not an enhancement. I'm changing the title to reflect the defect you're reporting.
> 
> More clarifications:
> 
> * Which one of the three writing modes are you choosing in settings that is causing the issue? (I couldn't determine which you selected)
> * Which locale have you chosen in the locale chooser? (English, Spanish, Chinese, or some combination)?
> 
> The intended behavior is that when you choose Chinese, and you choose vertical right-to-left, it should render correctly. For example, when I choose Chinese, choose vertical right to left in settings, and enter this program:
> 
> `Phrase("国际化活动W３Ｃ万维网联盟")`
> 
> This is what I see:
> 
> <img alt="image" width="222" src="https://user-images.githubusercontent.com/552276/278370128-b9effb4a-1d13-4314-9020-f573230681af.png">
> Do you see something different when following these steps?
> 
> A few tasks for you:
> 
> * Check the reproduction steps I provided above
> * If you see something different, change the description above to include the reproduction steps and add exact details of what browser version and operating system version you are using. We might just disallow the unhelpful layout option when  we use Latin script. 
> 
> If you _do_ see what I see, then this is a design issue, as it wasn't clear how to get Chinese text to render as you intended. If that's the case, then we have to do some redesign to make it clearer than the current approach (choose Chinese, change to vertical rtl).
> 
> If you _do not_ see what I see, then this is a defect, and something in your browser or OS is causing the difference.

I can't access any other locale besides English and Spanish. I just thought the current vertical layout made less sense in Latin script since it merely flips the text 90 degrees. I am kind of worried about whether implementing in CJK causes a similar issue. So I conceived a potential issue. The one below:
a wrong case:
截屏2023-10-25 21 38 39
But seeing your reply,  I think implementing this " Phrase("国际化活动W３Ｃ万维网联盟")" returns the correct output.  Therefore, no current concern on CJK's vertical layout.

**Comment by amyjko** [comment]
Ah, so this issue *isn't* about CJK? I'm getting very confused, sorry!

Yes, there's no reason someone using a Latin script would want to switch to vertical right to left writing mode. (They may want to do the vertical layout you portrayed, but they can do that with a `Stack()` layout).


I still think there are a few separate issues worth reporting here though:

* You've raised a different issue: why can't you choose a locale other than English and Spanish? Chinese is included currently. Are you not seeing it as an option? If not, please file a separate issue.
* Some Latin script users may use the writing mode setting expecting some functionality that is not intended. (It sounds like that is the issue you were originally reporting). Can you revise this issue's description to clarify that?
* There are definitely opportunities to enhance support for CJK scripts. Currently, the writing mode setting is global, but someone may want their code editor left to right, and some but not all of their stage output vertical right to left. It would be helpful to report an enhancement issue for that flexibility/

**Comment by amyjko** [comment]
I worked through the various problems raised in this issue and arrived at the following design:

* We should remove the global writing mode; it is not helpful
* The page should generally set the text direction to the primary script (left to right, right to left)
* The editor should respect the writing mode of the primary script, as code will likely be written in that script
* The output should not set a writing mode
* Phrases should have a writing mode that can be set individually to allow for vertical layouts
