### ISSUE TITLE
Floating dots on Gallery Page

### ISSUE THREAD

**Issue by erinmiso** [wordplaydev/wordplay#222]
## Expected behavior

I'm assuming the three dots are there so if the user clicks on the dots, it leads them to a page with more projects. 

## Actual behavior

Go to the Gallery page and scroll down to the Visualizations section. If you click on the three floating dots right next to the last project, the cursor pointer changes to a typing cursor and stays on the Gallery page.

## Screenshots
<img width="1254" alt="Screenshot 2023-10-24 at 6 02 40 PM" src="https://github.com/wordplaydev/wordplay/assets/146692565/42e24b49-51e0-4952-b284-94b4b8c69ca6">

## Environment

Desktop
mac OS Sonoma 14.0
Safari Version 17.0

**Comment by amyjko** [comment]
Thanks! This needs a redesign; those dots are not intended to be interactive, they just indicate that the gallery has more projects that aren't shown. But it sounds like it's reasonable to expect that they would be interactive, given ellison conventions in other UI's, so we could just turn that into a link, just like the gallery title is a link.

This is an easy fix; I'll implement today.
