### ISSUE TITLE
Changing story tab defaults to full screen

### ISSUE THREAD

**Issue by bwmendo** [wordplaydev/wordplay#223]
## Expected behavior

When you change the scene tab (for example – "The Verse – Program" to "The Verse – Placeholder") it will default to the split screen (scene tab, then coding space, then visualization).

## Actual behavior

When changing the scene tab, it will default to show the visualization on full screen.

1. Go to "Learn"
2. Click on the change scene arrow (dropdown arrow next to the left and right arrows, close to the "Learn" icon)
3. Click on a different tab than you are currently on "The Verse – Program" to "The Verse – Placeholder")

## Environment

Google Chrome v118.0.5993.88
MacOS Ventura v13.1

**Comment by amyjko** [comment]
Thanks! This is a regression from a fix I made yesterday to a different issue. My fault, I'll repair it today.
