### ISSUE TITLE
Duplicate concept appears in breadcrumbs after concept link click

### ISSUE THREAD

**Issue by Marc0Guo** [wordplaydev/wordplay#226]
Expected behavior
I'm not sure if that was done by design, but I expected to get only one "structure" on the middle of the page after I single click structure button. See picture 1.

Actual behavior
Go to learn - callback - structure - 16/19, click structure. It normally shows two by one click, but I accidentally got one for single click.

Screenshots
<img width="1440" alt="截屏2023-10-24 下午6 23 39" src="https://github.com/wordplaydev/wordplay/assets/146252292/c4669d0c-4902-41ae-9e39-1caf5b1ecd41">

Environment

Device: macbook pro, intel chip
OS: macOS 12.6.6
Browser: Firefox
Version: 118.0.1

**Comment by amyjko** [comment]
Clarifications:

* What "structure" are you clicking in these reproduction steps? The link in the tutorial dialog after "a Game"?
* What does "normally shows two" mean? Shows two of what? And what does does "got one" mean?

Go ahead and revise the description above instead of adding a comment.

**Comment by amyjko** [comment]
@Marc0Guo I'd love to have clarifications on these; we can't fix them without these clarifications. Thanks!

**Comment by amyjko** [comment]
I'm going to guess what this issues refers to:

* Find a concept link in the tutorial or documentation
* Click on the link
* Two links appear in the documentation breadcrumbs instead of one, the second a duplicate

If this is not the issue reported, please reopen and clarify. Thanks!
