### ISSUE TITLE
Color Selector Inconsistencies

### ISSUE THREAD

**Issue by andrea-dan** [wordplaydev/wordplay#227]
## Expected behavior

Users should be able to either 1. browse the gradient selector to pick a color, 2. choose a hardcoded color from the square palette, or 3. toggle the LCH slide selectors until they reach a desired color, and have that color be displayed in the preview square on the left as well as in their phrase's actual color. Additionally, as users toggle the sliders or even drag their picker against the gradient, the slider values should change with the users movements.

## Actual behavior

First:

1. Click on palette
2. Edit the color of your phrase

Then, we can observe the following problems:

The preview square doesn't display the color selected by the user - clicking from black to other colors, specifically orange, causes issues.

Then, as users toggle the sliders or even drag their picker against the gradient, the slider values just flicker back and forth like crazy.

## Screenshots
![image](https://github.com/wordplaydev/wordplay/assets/125759437/183fd78e-d1a8-416d-a708-10889ffe4785)
![image](https://github.com/wordplaydev/wordplay/assets/125759437/66b247ba-170d-4124-a46c-ce8f0ace683e)

## Environment
Laptop, Windows 10, Chrome 118

**Comment by amyjko** [comment]
Thanks for the detailed report! it sounds like the color chooser is comprehensively misbehaving. I'll investigate and repair.

**Comment by amyjko** [comment]
Found and fixed four defects:

* Lightness was not being converted between percents and 0-1 values correctly in three places
* There was a missing dependency in Svelte reactive statement in `BindColor`

All of these should be fixed now.
