### ISSUE TITLE
Some Unicode Regular Expression Layouts are difficult to parse visually

### ISSUE THREAD

**Issue by orcmid** [wordplaydev/wordplay#243]
## Expected behavior

Being able to see the separation of glyphs in the presented form of certain Unicode-glyph patterns.

## Actual behavior

In `LANGUAGE.md` line 67, the distinction of the Roman Numerals as separate Unicode glyphs is not evident.  It requires being able to step through them with the cursor to see what's happening, and I think that might require edit mode.

## Question

Is it possible to adjust the grammar so that spaces can occur without disturbing the pattern or maybe not use a regular expression in this case?

It may be more difficult than that.  The Roman numerals I, V, X, L, C, D, and M are rather indistinguishable from the Roman letters having the same glyphs.

**Comment by amyjko** [comment]
This is mostly a typography issue: if GitHub were using a font that properly rendered the casing of Roman numerals, the glyph boundaries would be visible. (Try copying and pasting in an editor with a different font, and you'll see casing differences).

I'll put grouping separators to make it clear.
