### ISSUE TITLE
Incomplete textopen/textclose lexicals

### ISSUE THREAD

**Issue by orcmid** [wordplaydev/wordplay#245]
## Expected behavior

It would expect that one could do text open/close pairings such as ⎾ …  ⏋as well as the inverted ones and the double-bar ones.

## Actual behavior

The available open/close pairings seem to be restricted for no reason, among those glyphs that are included.  (There are others that have no representative in the lexical structure.  I am not lobbying for that.)

**Comment by amyjko** [comment]
We didn't include pairs of top and bottom because they generally aren't used that way in any scripts globally. If you're aware of a language that uses them that way, this is a reasonable addition.

**Comment by orcmid** [comment]
@amyjko 
> We didn't include pairs of top and bottom because they generally aren't used that way in any scripts globally. If you're aware of a language that uses them that way, this is a reasonable addition.

I encountered them being used that way in mathematical and symbolic-logic notations.  I suppose they are not intended to signify literal quotation, if that is what open-close is limited to here.   I didn't stop to wonder where [ ... ] and { ... } go, if anywhere.  I suppose the usages I am aware of might be relegated to comments.

**Comment by amyjko** [comment]
Text open and text close delimiters are for text literals, not for math notations. This programming language is primarily about text, not math. The square and curly brackets are used for lists and sets, respectively, not for text literals.
