### ISSUE TITLE
Discolored Drop down menu

### ISSUE THREAD

**Issue by RuweydaAbdi** [wordplaydev/wordplay#251]
Some laptops would show a gray background color for the dropdown menu, while some like mine would show a orange background color. Amy mentioned that she never told it to be orange, so its unsure why this bug is the way it is. This issue is located in the "Learn" tab. Here is a screenshot of the issue: 
<img width="341" alt="image" src="https://github.com/wordplaydev/wordplay/assets/146573912/6110a83e-7a03-439e-8875-8d95f4fc4370">

My environment: I am using google chrome, ASUS vivobook s14, windows 11, version: 22H2, OS: 22621.2428

**Comment by amyjko** [comment]
Thanks for reporting! It's an interesting CSS mystery.

**Comment by amyjko** [comment]
Resolved by acf38eb7b.
