### ISSUE TITLE
Safari not rendering Noto Emoji, falling back to Apple Emoji

### ISSUE THREAD

**Issue by amyjko** [wordplaydev/wordplay#252]
## Expected behavior

We've specified "Noto Emoji" as a fallback font for the application and code fonts, and they should be used for any emoji that appear.

## Actual behavior

All emoji in the application use Apple Color Emoji instead of Noto Emoji:

## Screenshots

<img width="363" alt="image" src="https://github.com/wordplaydev/wordplay/assets/552276/52efd4d5-1508-406d-8eca-4f2ee3502088">

<img width="337" alt="image" src="https://github.com/wordplaydev/wordplay/assets/552276/fd3e9d13-acfd-4c49-b12c-8d1af9dc95d1">

## Environment

Desktop

-   macOS 14.0
-   Safary 17.0

## Cause

After some reading:

* https://www.stefanjudis.com/snippets/how-to-detect-emojis-in-javascript-strings/
* https://stackoverflow.com/questions/24061808/google-font-not-working-on-safari
* https://stackoverflow.com/questions/14889045/safari-and-ie-cant-read-ttf-and-eot-fonts
* https://bugs.webkit.org/show_bug.cgi?id=258877

I've determined that when Safari doesn't find a U+FE0F or U+FE0E variation selector at the end of the emoji, it treats it as a text emoji, and does not find such an emoji in any of the specified fonts, and so it falls back to the system emoji font. This doesn't occur on Chrome likely because of how the font is specified; perhaps Chrome interprets the font file differently.

One workaround is simply adding either U+FE0F or U+FE0E to any emoji that appear in anything rendered. Then Safari uses the font correctly.

**Comment by teewuane** [comment]
To be clear, you find the emoji characters in your string of text and then add U+FEOF or U+FEOE after the emoji character?

Do you have an example of how you do this? How do you determine if the character is indeed an emoji vs some other character?

**Comment by amyjko** [comment]
Oh, look at this old bug you found! I'm pretty sure it hasn't been fixed in Safari yet. You can see our workaround here:

https://github.com/wordplaydev/wordplay/blob/main/src/unicode/emoji.ts

* We strip any variation selections that might be present
* We use a regex to detect most things that qualify as emoji (this isn't perfect, but better than the precise and full list), then append the preferred variation selector after it.

You can learn more about the intended variation selector syntax and semantics here:

https://www.unicode.org/reports/tr37/

There are some ambiguities about font fallback behavior in the spec, hence the different behaviors in Webkit, Chromium, and Firefox.
