### ISSUE TITLE
Requirement to view password in username/password account creation is unclear

### ISSUE THREAD

**Issue by amyjko** [wordplaydev/wordplay#255]
## Expected behavior

When creators type in a username and password then press enter, it should be clear that they need to view the password they entered before the create button is enabled.

## Actual behavior

It's not clear. One user kept clicking the button, but not reading the message that said that they needed to view their password, and didn't understand why they needed to view it.

## Fix

One possible redesign might be changing the label to indicate that they need to review their password.

**Comment by mikeaustin** [comment]
@amyjko When you say "but not reading the message that said that they needed to view their password", I don't quite understand what you mean. How do you "check your password"? "submit again".. I tried clicking the >> but nothing happened.

![image](https://github.com/wordplaydev/wordplay/assets/343144/d431cdb7-8e28-4c00-9258-944c3d1e44c0)

**Comment by mikeaustin** [comment]
One part of the issue is that you can click on and tab to disabled buttons which highlight in orange. After looking closer, I see the text is a lighter gray, but in terms of accessibility, it's difficult to tell that it's disabled.

**Comment by amyjko** [comment]
Thanks @mikeaustin! We recently changed the text to say:

> To create your account, select your password above to reveal it, and make sure you stored it safely and correctly. Then submit again to create your account.

The intended interaction is that someone clicks to reveal their password to reveal it, and once revealed, the button is enabled. This is a slightly unconventional interaction that ensures that people don't create their account without incorrectly capturing the password they chose, and a design that has been recommended over having people enter it twice (which isn't very effective at catching these issues). We're open to other designs that prevent lockout; the key thing is that the user checks and verifies their password before its submitted and they're logged in.

The disabled button issue is definitely a complicating factor here; we don't give it the `disabled` attribute because of the way that hides buttons from screen readers.

**Comment by amyjko** [comment]
This was clarified in a redesign. There are definitely opportunities for further improvement, but a few usability tests on the new design seemed to have resolved any confusion.
