### ISSUE TITLE
Gallery Projects Not Loading and/or Lagging

### ISSUE THREAD

**Issue by soniadashti** [wordplaydev/wordplay#258]
## Expected behavior

When I select a gallery project, I expect it to open up the project I selected.

## Actual behavior
To repeat the behavior: 

1. Go to Galleries
2. Click on a project, for example: "Womens Literacy Rates"
3. See if it loads

At the moment, when I select project, like the Womens Literacy Rates for example, it either does not open or it opens slowly. This is a random occurrence, as there are times projects load fine and sometimes they don't. When it does not load, it may also cause the gallery to freeze or not display data fully.

## Screenshots

Here is an example of what happened one of the times while I was trying to click a project: 
<img width="1205" alt="Screen Shot 2023-11-01 at 10 25 18 PM" src="https://github.com/wordplaydev/wordplay/assets/97253346/6baab1fc-57c9-4edd-98f7-ff12a09c899d">

As you can see, the audio/video category stopped loading and the title of the Tools category completely disappeared after I selected a project. Prior to selecting the project, all of the images and titles were there. This data eventually comes back or the page will reload. 

## Environment

Safari on MacOS Version 12.6 (21G115)

**Comment by amyjko** [comment]
Thanks @soniadashti! Can you share what your device is, so we have a sense of performance capabilities? I suspect this is a performance issue.

**Comment by soniadashti** [comment]
@amyjko I am on a Macbook Air (M1, 2020)
