### ISSUE TITLE
Login Password does not allow revision

### ISSUE THREAD

**Issue by KaidiKelsey** [wordplaydev/wordplay#272]
## Expected behavior

It said that "to create your account, select your password above to reveal it, and make sure you stored it safely and correctly. Then submit again to create your account." However, if the password is incorrect and has typos, I cannot change it. 

## Actual behavior

1. Go to https://wordplay.dev/
2. Click on login
3. type username and password
4. click the arrow and cannot change the password
## Screenshots
<img width="807" alt="Screenshot 2023-11-06 at 4 08 06 PM" src="https://github.com/wordplaydev/wordplay/assets/97130417/f6142dc3-e8f6-428c-8b70-3b3633e28b8b">

## Environment

What platform, OS, browser, and version are you using? Please be exact with version numbers, as different versions can result in a defect happening or not. Don't skip these; cross-browser issues are a common cause of problems.

Desktop

-   Macbook PRO: 14.0 (23A344)

**Comment by amyjko** [comment]
Ah, good catch, this should definitely be possible. My design flaw, I'll fix it.
