### ISSUE TITLE
Request for wording notification of incorrect username and password

### ISSUE THREAD

**Issue by KaidiKelsey** [wordplaydev/wordplay#273]
## What's the problem?

When I enter username or password and not follow the requirement, it just shows the username and password in orange without any wording notification, which could first confuse the users. 

## What's the design idea?

Maybe could have similar wording notification box pop up.
<img width="807" alt="Screenshot 2023-11-06 at 4 08 06 PM" src="https://github.com/wordplaydev/wordplay/assets/97130417/ad009e64-0c0e-4e24-b5d2-1c732fd00e1e">

## Who benefits?

The users who make mistakes when they enter username and password.

**Comment by amyjko** [comment]
Can you clarify the aspect of this that's confusing? Is the problem with the orange warning text, or something else? What does "wording notification" mean in the description above?

**Comment by KaidiKelsey** [comment]
Sorry for the unclear clarification. What I mean here is that it just show my wrong username and password in orange (p1) without any text telling me that my username and password did not fit the requirement. I am thinking we could have some pop-up window to say it or have some notification in text like p2 the orange box,

p1
<img width="715" alt="Screenshot 2023-11-07 at 10 48 02 AM" src="https://github.com/wordplaydev/wordplay/assets/97130417/1d9a5fbd-fcaf-42c4-a34f-a7eb921d9eba">


p2
<img width="807" alt="Screenshot 2023-11-06 at 4 08 06 PM" src="https://github.com/wordplaydev/wordplay/assets/97130417/1eba657c-b92c-4669-85cf-7298e2b3ebc3">

**Comment by amyjko** [comment]
Ah, thank you for the clarification! If I understand correctly, your proposal is to provide better error feedback when the form is not valid. If that's correct, I agree.
