### ISSUE TITLE
Noto color emoji not rendering in Safari

### ISSUE THREAD

**Issue by Marc0Guo** [wordplaydev/wordplay#274]
## Expected behavior

When I logged into my account and go to account setting pages, I took a look at "Pick an emoji to represent yourself to others." There should be emoji coming up, but I didn't see anything. 

## Actual behavior

I logged into my account go to my account page and check "Pick an emoji to represent yourself to others." When my curser moved on to that region, the emoji name came up, so the only problem here is the emoji picture. Besides that, when I'm using my phone, the emoji name didn't pop up as expected. I hold my finger on the gray box for several seconds and the name doesn't show up.

## Screenshots
![IMG_DF3BCD08FF8D-1](https://github.com/wordplaydev/wordplay/assets/146252292/ea99f622-6e5b-4bb7-94f9-38cde079d492)

<img width="1190" alt="截屏2023-11-07 下午5 54 36" src="https://github.com/wordplaydev/wordplay/assets/146252292/3d4de266-eed0-4bc8-b678-10f8d605f272">

## Environment

What platform, OS, browser, and version are you using? Please be exact with version numbers, as different versions can result in a defect happening or not. Don't skip these; cross-browser issues are a common cause of problems.

Desktop

-   OS + version: Mac OS 12.6.6
-   Browser + version Safari 16.5

Smartphone

-   Device: iPhone 12 pro
-   OS + version: iOS  16.6.1
-   Browser + version Safari 16.5

**Comment by amyjko** [comment]
Can you check the safari web inspector and see if there are any errors reported on the console or in the Network tab? This would happen if the font were not successfully downloaded, or not finished downloading.

**Comment by amyjko** [comment]
@Marc0Guo Scratch that, I was able to reproduce in Safari 17.0. Looks like a font file issue. I'll investigate.
