### ISSUE TITLE
Copy & paste don't work in Firefox

### ISSUE THREAD

**Issue by willowsalicaceae** [wordplaydev/wordplay#285]
## Expected behavior

The copy and paste buttons and keyboard shortcuts should work within the Wordplay editor.

## Actual behavior

1. Go to any project
2. Open the editor
3. Click the 'copy selection' or 'paste contents of keyboard' buttons or use the keyboard shortcuts
4. Nothing can be copied or pasted

## Environment

Desktop

-   Windows 11 22H2
-   Firefox 119.0.1

**Comment by amyjko** [comment]
Thanks @willowsalicaceae! Confirmed that copy and paste does work externally from the clipboard, but not for content copied and pasted from the editor.
