### ISSUE TITLE
Gallery Topics Image link not taking you anywhere

### ISSUE THREAD

**Issue by soniadashti** [wordplaydev/wordplay#286]
## Expected behavior

When you go in the gallery and attempt to click a topic such as Tools, if you choose to click the topic by selecting the big image to left of the topic name, you would expect it to link/take you to the Tools gallery. 

## Actual behavior

1. Go to galleries
2. Click on the image to the left of "Tools"
3. Get an "Eep!" warning OR you see the Tools gallery (sometimes it works and takes you to the list of projects under "Tools" and sometimes you receive an error) 

## Screenshots
Here is a photo reference of the error when it does not link you to anywhere when the image is clicked on. 

<img width="1437" alt="Screen Shot 2023-11-14 at 6 13 38 PM" src="https://github.com/wordplaydev/wordplay/assets/97253346/7bb519f5-04d1-4c8d-b28d-aa5c97aba19d">

## Environment
 
Device: Macbook Air (M1, 2020), MacOS Monterey Version 12.6 (21G115)

Browser: Safari

**Comment by amyjko** [comment]
Thanks @soniadashti. I can't reproduce this. If you can, can you share what URL you're getting "Eep!" on? The url should be `https://wordplay.dev/gallery/Tools`.

**Comment by soniadashti** [comment]
@amyjko, the link when I get the "Eep!" is `https://wordplay.dev/project/gallery/Tools`.

It seems as though it adds a `/project`. When it does work, the link does not include this part. I would like to add, this same issue is happening on my Iphone 12 as well.

**Comment by amyjko** [comment]
Thanks! I can reproduce now.
