### ISSUE TITLE
Missing localization on icons

### ISSUE THREAD

**Issue by yz425-2036461** [wordplaydev/wordplay#293]
## Expected behavior

The hover of three icons grid, zoom, and full size should be in the language the user chose.

## Actual behavior

The hover stays in English in other language modes as well.

1. Go to 'Project'
2. Changed to Mandarin/Spanish mode
3. Open the editor
4. Move the cursor onto those three icons
5. The hover is still in English

## Screenshots
<img width="724" alt="Screen Shot 2023-11-22 at 12 01 23 AM" src="https://github.com/wordplaydev/wordplay/assets/97197991/a4778b45-4a2c-4cad-81d7-d818cbe921b4">
<img width="719" alt="Screen Shot 2023-11-22 at 12 02 53 AM" src="https://github.com/wordplaydev/wordplay/assets/97197991/150aed21-a4ae-4088-a0b7-a5011441268f">
<img width="720" alt="Screen Shot 2023-11-22 at 12 03 02 AM" src="https://github.com/wordplaydev/wordplay/assets/97197991/6e249211-7ed7-45ce-a750-70c2eaf0667d">

## Environment

Mac OS 11.6
Chrome Version 119.0.6045.123

**Comment by amyjko** [comment]
Thanks for reporting!
