### ISSUE TITLE
Delete account feature not showing feedback for invalid email/username

### ISSUE THREAD

**Issue by Marc0Guo** [wordplaydev/wordplay#296]
## Expected behavior

The delete account feature is expected to show me an error message saying like "the email/username doesn't exist" when I put incorrect email/username in it. But it only showed me the light gray box that I couldn't click on.

## Actual behavior

Go to account page, click delete my data, type "marco.guojiawei@outlook.com" (an account that has been deleted) into the text box. Nothing happened as I click the "delete it!!!" button.

Error message in console: 
Fetch API cannot load https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?gsessionid=oWwxhv-opU648zOlGqqJpTKP-BQUBfOpUw4Lep9CnKY&VER=8&database=projects%2Fwordplay-prod%2Fdatabases%2F(default)&RID=rpc&SID=j9Hw9cQE8Obvi9DL6pnMMA&AID=17&CI=0&TYPE=xmlhttp&zx=tbmkhut1sx9&t=1 due to access control checks.
Fetch API cannot load https://firestore.googleapis.com/google.firestore.v1.Firestore/Listen/channel?gsessionid=oWwxhv-opU648zOlGqqJpTKP-BQUBfOpUw4Lep9CnKY&VER=8&database=projects%2Fwordplay-prod%2Fdatabases%2F(default)&RID=rpc&SID=j9Hw9cQE8Obvi9DL6pnMMA&AID=17&CI=0&TYPE=xmlhttp&zx=auhm42gtah8p&t=2 due to access control checks.

## Screenshots
![IMG_6948](https://github.com/wordplaydev/wordplay/assets/146252292/d100b4d3-321a-45c5-b683-8f4091d5b58c)

<img width="1440" alt="截屏2023-11-28 下午5 00 37" src="https://github.com/wordplaydev/wordplay/assets/146252292/94dec92d-e4f6-4b4c-add1-abf0c8c15dbb">

## Environment

Desktop

OS + version: Mac OS 12.6.6
Browser + version Safari 16.5
Smartphone

Device: iPhone 12 pro
OS + version: iOS 16.6.1
Browser + version Safari 16.5

**Comment by amyjko** [comment]
1. Please add exact reproduction steps
2. Please file a separate issue for the feature request ideas.
