### ISSUE TITLE
username size adjustment

### ISSUE THREAD

**Issue by huangzi11** [wordplaydev/wordplay#297]
## What's the problem?

When I log into the website and view my profile page, the headline, which appears to be an email address (example: "abcdefg@uw.edu", is not displaying correctly. The last character of the email address ("g" in this case) is consistently breaking onto a new line, disrupting the readability and visual appeal of the page.
## What's the design idea?

A potential fix could be adjusting the CSS properties, such as word-wrap, overflow-wrap, or increasing the width of the container that holds the email address. This would ensure that the entire email address is displayed on a single line, improving readability and overall presentation.

## Who benefits?

The overall user experience will be enhanced, reflecting positively on the website's professionalism and attention to detail.

## Issue IMG 
<img width="1369" alt="Screenshot 2023-11-28 at 5 41 34 PM" src="https://github.com/wordplaydev/wordplay/assets/97570391/b6d78468-bf88-4aa6-813c-1730854a416f">

**Comment by shiinasugioka** [comment]
note to future devs: can't test this on localhost without modifying firebase settings... Need to be connected to the server in order to be able to login and test this screen

**Comment by shiinasugioka** [comment]
@amyjko Is there a way for us to be able to login on local host or test our changes on some branch that is connected to a server? This particular issue requires testing a post-login screen

**Comment by amyjko** [comment]
See the setup wiki for details on running the Firebase emulator: 

https://github.com/wordplaydev/wordplay/wiki/setup

For this issue, note that we can't have long emails/usernames on a single line without causing the page to scroll horizontally. That's why it wraps by character currently. The alternatives are: 1) truncate, 2) reduce the size of the font to fit it to the width of the page.

**Comment by amyjko** [comment]
Fixed the labels; this is a defect, not a feature request.

**Comment by huangzi11** [comment]
> @huangzi11 Any reason you closed this? It's still a design defect.

Sorry it was my mistake

**Comment by amyjko** [comment]
Hi @shiinasugioka and @wkxdavid!

It's the end of the quarter, so please post an update on this issue. Things to consider:

* Should you still be the assignee? (If you're planning on working on it, yes! Submit a comment explaining your plans. If not, then unassign yourself, so others are eligible to grab it).
* Do you have any work products that are hosted outside of GitHub? Embed them in this issue, so others can build off of them.
* Are there any branches associated with this issue? Please link to them in the issue.

If there's nothing to change above, then at least post a comment indicating that you've seen this. Thanks!

**Comment by amyjko** [comment]
No reply, unassigning everyone to free up the issue for others to work on.

**Comment by amyjko** [comment]
Closing issue. The only alternative is to have the username not break, which causes the page to scroll horizontally.
