### ISSUE TITLE
Adding collaborators does not work

### ISSUE THREAD

**Issue by jibsamoun** [wordplaydev/wordplay#301]
## Expected behavior

When adding collaborators, the owner should be able to add via email or username. Once the invite is sent to the contributors, the owner's project should appear within the given contributors' "Projects" space. 

### Owner's POV

Username: Yding25

1. Click on "Projects" 
2. Click on any given project
3. Click on privacy button - should be labeled "private" or "public"
4. Under "Collaborators" section - input contributors Wordplay username or email attached to their account, and click the arrow to send

### Contributor's POV

Username: jbmoun2003

1. Click on "Projects"
2. Owner's project does not appear 

### Summary
Shared projects are NOT appearing in recipient's "Projects" space.

### Owner's POV - Yding25

![480948D5-4A5F-4696-A98C-91F0AF6B4143](https://github.com/wordplaydev/wordplay/assets/146492078/cbb75dff-e0d4-497f-816a-9fd384217fe0)

### Recipient Contributor's POV - jbmoun2003

![3456C9CB-7002-46D0-9D91-72B835026A1E](https://github.com/wordplaydev/wordplay/assets/146492078/388a4b20-35d9-4b9a-85d6-0b372eb056fb)

## Environment

Desktop

Owner: Yding25
-   macOS Monterey 12.1
-   Chrome Version 119.0.6045.159

Contributor Recipient: jbmoun2003
-  macOS Monterey 12.5
-  Chrome Version 119.0.6045.159

**Comment by amyjko** [comment]
Should be resolved now. It was caused by a schema validation bug.
