### ISSUE TITLE
Accessibility suggestion: Include a brief description of the displayed content or visual for screen reader

### ISSUE THREAD

**Issue by MichelleGuan1128** [wordplaydev/wordplay#315]
## Expected behavior

Expected to hear a description output via the screen reader.

When trying to use the Galleries section, I struggled to understand the displayed content on the page using a screen reader.

## Actual behavior
1. Turn on screen reader.
2. Navigate to 'Galleries'.
3. Click on any section within Game, Visualizations, Motion, Audio/Video, or Tools.
4. The screen reader does not tell the user what happened on the page.

## Screenshots

<img width="1440" alt="Screenshot 2023-12-05 at 1 39 52 PM" src="https://github.com/wordplaydev/wordplay/assets/76934364/f5a48543-8a18-47b5-a851-74861a5a5d77">

## Environment

Device: MacBook Pro Intel Core i5
OS: MacOS 14.0
Browser FireFox
Version 118.0.2

**Comment by amyjko** [comment]
@MichelleGuan1128 Can you clarify your reproduction steps? They seem to include selecting a gallery to view, but the screenshot shows a program's output. What are you expecting the screen reader to read, the program output or the gallery view? And if the gallery view, what specific thing in the gallery is not being read?

**Comment by amyjko** [comment]
@MichelleGuan1128, can you answer the question above?

**Comment by amyjko** [comment]
No answer. @MichelleGuan1128, if you can clarify, please reopen so we know what this issue is referring to.
