### ISSUE TITLE
Test Chinese UI

### ISSUE THREAD

**Issue by benjaminmeow** [wordplaydev/wordplay#317]
## Expected behavior

All of the Chinese characters should be rendered and be properly formatted in a readable way. 

## Actual behavior

This has not been tested at all. It is very unclear if it renders at all right now. There are no known issues, but since there has been no manual verification, we expect there to be at least some user interface issues with the localization strings, particularly layout issues.

**Comment by awang040403** [comment]
Hi @amyjko, I am interested in working on this issue. Could you please assign me to it?
