### ISSUE TITLE
Remove non PII strings from project

### ISSUE THREAD

**Issue by amyjko** [wordplaydev/wordplay#331]
## What's the problem?

When personally identifiable information appears in text, we show conflicts that allow creators to mark it as not sensitive. Creators may mark it as not sensitive on accident, or it may change in sensitivity, and so there should be a way to unmark text as not sensitive.

## What's the design idea?

In the sharing dialog, we could show a list of strings marked as not sensitive and include a delete button next to them, allowing the set of strings to be edited.

## Who benefits?

Anyone sensitive about the privacy of their data, and other indirect stakeholders who are, such as teachers.

## Design specification

For Projects, we keep track of a list of phrases that have been marked as non PII by the creator (stored in array called nonPII) through the conflict resolution for PII (see related issue: [#310](https://github.com/wordplaydev/wordplay/issues/310)). So in the sharing dialog, we can create a new section displaying all these phrases with a button next to each of them to unmark the text as non PII and add a `PossiblePII` conflict back to that text. This section will also have a reminder to make sure creators know that unmarking text as non PII means that the project will not be saved online anymore.

<img alt="sharing dialog proposal with personal information section at the bottom" src="https://github.com/wordplaydev/wordplay/assets/77032464/ba4489d6-bddb-4c19-9fa5-e83959bd31d5" />

Additionally, to ensure that creators know where they can unmark text as non-sensitive, we can add a note to the conflict resolution reminding them where they can manage PII in their project. 
<img alt="help and conflicts section with updated message telling creators where they can unmark text as non-sensitive" src="https://github.com/wordplaydev/wordplay/assets/77032464/69b20216-c101-40dc-b0be-2c620c44f2dc" />

**Comment by lwong121** [comment]
Hi @amyjko! Above is my initial design based on what I could find from the issue description, related issue, and code. But I would really appreciate any suggestions or feedback on it especially since you worked on the conflict resolutions for PossiblePII. Thanks!

**Comment by amyjko** [comment]
Thanks @lwong121! I like the simplicity of it, and the label you chose; I think that language is consistent with the rest of the language we've used.

A few things to ponder:

* To add strings to the 'not sensitive' list, they click a button in a conflict warning. But to remove it, they have to come to the sharing dialog. The asymmetry of that could be a usability issue, since it's not quite clear once they click the conflict resolution button how they might undo that if it were an accident. One remedy to that might be to put a link in the conflict resolution UI to say "You can see other things you've marked not sensitive in the sharing dialog", and basically teach it. Can you think of some other way to make marking and unmarking these more symmetrical?

* The effect of marking something sensitive, if the text still appears in the program, is that the program won't be saved online. It might be smart for us to put some feedback in the sharing dialog about that, warning that if they remove it, the project won't be saved in the cloud anymore.

**Comment by lwong121** [comment]
Thanks @amyjko for the great feedback! Here are some of my thoughts on the points you mentioned. Please take a look whenever you get the chance. Thanks! 

**Can you think of some other way to make marking and unmarking these more symmetrical?**
I agree with your point, it is not going to be very clear how creators can unmark non-sensitive text. Below are just a few ideas I could think of with my knowledge of Wordplay and the UI. But I would be open to any other ideas too. 

- Idea 1 (as you mentioned): Add directions in the original conflict resolution to say “You can see other things you've marked not sensitive in the sharing dialog.” 
    - This is definitely the easiest solution, but it is not the most intuitive because we have to teach them where to find it and some creators might miss the note making it hard to figure out where they can unmark it.  
- Idea 2: If the project contains text marked as not sensitive, add a dialog in the conflicts/help section indicating that there is still possible PII marked as non-sensitive and direct creators to the sharing dialog. 
    - Similar to the first solution, but it solves the second issue for idea 1 because the dialog/annotation will not go away until there is no possible PII left (even if it is marked as non-sensitive) so it is more likely that creators will see it. But this might add unnecessary clutter to the conflicts and help section. 
- Idea 3: When the user marks text as not sensitive, replace the conflict resolution with an annotation that gives creators 2 options: ignore the message or unmark it as non-sensitive. 
    - It helps make marking/unmarking a lot more symmetrical because creators can complete both tasks in the same place using the same method. But it might be cluttered and confusing for creators especially when there are many annotations. It could also get annoying for creators who just want to mark the text as non-sensitive and get rid of the annotation but are forced to essentially resolve the same conflict twice (which is why I’m not too sure about this idea). 

**Add a warning to sharing dialog saying that project won't be saved if there is still text marked as sensitive**
That makes sense to add because it is not immediately clear. Thanks for catching that. I updated the UI design image to include a warning in the personal information section of the sharing dialog. :)

**Comment by amyjko** [comment]
Great ideation! I think given the caveats to ideas 2 and 3, idea 1 is going to have to be the design. Both 2 and 3 would change the behavior of the conflicts dialog a lot, and introduce a lot of complexity. Clear communication about where PII is managed (the sharing dialog) is probably the best strategy.

Update the design accordingly and I think I'm ready to approve this design.

**Comment by lwong121** [comment]
Thanks! I have updated the design specification to include this new information.

**Comment by amyjko** [comment]
Okay, it looks good! Design approved for building.

**Comment by lwong121** [comment]
Okay, I have added the ability for users to unmark text as non-sensitive through the sharing dialog. Now when a user clicks on the "sensitive" button next to some text they previously marked as nonPII, it is removed from the nonPII list plus the sharing dialog and the PossiblePII conflict reappears in the conflicts section. I have verified that it works for different types of PII and that the nonPII list and sharing dialog are updated as expected through manual testing.

The branch I am working on is called **331-remove-nonPII**, I would really love to get some feedback before moving forward. Thanks!

Questions:
- How are translations typically handled within the team? Could I just ask members of the localization team to translate the new text I added and have them join as an assignee?

**Comment by amyjko** [comment]
Nice work, this is really thorough! A few comments:

* Process note: the way to get feedback is to submit a draft pull request, proposing to merge your branch to main. That makes reviewing easier, runs tests, etc. Check the dev wiki for guidelines on this and let me know if some part of it wasn't clear.
* The implementation is very thorough; you followed all of the standard parents, fit everything well into the existing implementation. I'm very impressed.
* The standard way to mark translations as needed is to add the new properties you've added to the other locales (`es-MX`, `example`, `zh-CHI`) so that `npm run locales` doesn't warn on missing properties, but leave them with placeholders `$?`, which marks them as unwritten. That causes them to default to English until translated. The localization wiki covers this syntax. We don't have a good workflow yet for launching with complete locales, since we don't have full language coverage of contributors on the localization side.

Submit the PR when you're ready, I think this is quite close.

**Comment by lwong121** [comment]
Thanks! I really tried to make use of existing widgets so that the experience is as consistent as possible and to follow the existing implementation so that the code remains consistent. :)

I have created a PR and added the translation placeholders in the files you mentioned. This was good information to know for future issues.
