### ISSUE TITLE
Resolve duplicate name

### ISSUE THREAD

**Issue by amyjko** [wordplaydev/wordplay#332]
## What's the problem?

When a declaration has a duplicate name, creators have to manually remove it to resolve the warning:

`name,name: 5`

## What's the design idea?

Add a conflict resolution for `DuplicateName` that removes one of the duplicates.

## Who benefits?

Anyone looking for a quick fix to the problem.

### Draft 2
Adding a prompt on the middle console, showing the user, "There is a duplicate name, do you want to change it to something else". Once the user changes the duplicated one, the warning goes away.

#### Normal case
<img width="500" alt="Screenshot 2024-02-07 at 17 55 24" src="https://github.com/wordplaydev/wordplay/assets/98635480/cca44217-c153-49b9-9c23-03dd2ca01663">

##### Solution
When there are duplicate names, there will be a prompt with a button on the middle console showing "There are duplicate names, do you want to remove it? Note: the duplicate names will never be beneficial to your program." Once the user clicks the check button, one duplicated name will be removed, and the warning will go away.

##### Prototype
<img width="500" alt="Screenshot 2024-02-07 at 18 12 07" src="https://github.com/wordplaydev/wordplay/assets/98635480/3c83fc1c-553a-471b-8e06-de47db57402c">

#### Edge Case 1 -- duplicate name with different languages
<img width="500" alt="Screenshot 2024-02-07 at 17 47 29" src="https://github.com/wordplaydev/wordplay/assets/98635480/4c133130-626c-40e1-9c5f-5f00269e0bd5">

##### Solution 1
Previligae the default language setting: 
* If the users set the default language as English, the prompt will show "There are duplicate names, do you want to keep the one in your default language? Note: the duplicate names will never be beneficial to your program."

##### Prototype
<img width="500" alt="Screenshot 2024-02-07 at 18 18 32" src="https://github.com/wordplaydev/wordplay/assets/98635480/09ae45ce-ac4b-4ef9-bcc2-801796ddbfa0">

##### Solution 2
Provide choices to users:
* The prompt will be "There are duplicate names, which one do you want to keep?  Note: the duplicate names will never be beneficial to your program". Users will be able to choose from the button to keep the one they wish.

##### Prototype
<img width="500" alt="Screenshot 2024-02-07 at 18 21 47" src="https://github.com/wordplaydev/wordplay/assets/98635480/cd71ee73-b106-464d-b53e-912f106b1421">

#### Normal case
<img width="500" alt="Screenshot 2024-02-07 at 17 55 24" src="https://github.com/wordplaydev/wordplay/assets/98635480/cca44217-c153-49b9-9c23-03dd2ca01663">

##### Solution
When there are duplicate names, there will be a prompt with a button on the middle console showing "There are duplicate names, do you want to remove it?" Once the user clicks the check button, one duplicated name will be removed, and the warning will go away.

##### Prototype
<img width="500" alt="Screenshot 2024-02-14 at 10 47 05" src="https://github.com/wordplaydev/wordplay/assets/98635480/9f107fee-4af1-4deb-b2f2-f95e2338dcaa">

**Comment by xmzeng00** [comment]
Hi Amy, could you point me some direction on where to start on this issue?

**Comment by amyjko** [comment]
Yep!

* First, make sure you've completed the whole tutorial, so you know a bit about how to use the programming language
* Next, make a project with a binding that has a duplicate name so you can see the conflict that appears. That's what this issue will enhance.
* Next, see an example of an existing conflict resolution. For example, try typing the program `email: 'ajko@uw.edu'`. It'll give a conflict that it seems to be personally identifiable information. There's an option there to say "No, it's not", and then the warning goes away. That's what this issue will create, but for duplicate names.
* I can't recall if you're designing or designing _and_ developing, but either way, start with design: what should the resolution button label be? What effect will pressing that button have? Once you've designed that, put a proposal in the main issue above and I can review and approve, and we can move on to development.
* If you're also building this, the key files are `DuplicateName.ts`, and the `Resolution` type in `Conflict.ts`. Everything you need to build is in `DuplicateName.ts`, returning a `Resoluttion` that revises the program to remove the duplicate name.

That should get you started.

**Comment by xmzeng00** [comment]
## Design specification Draft 1

### Design Idea
* Red underlines appear under the two duplicate names. When hovering over and clicking on the inputs, a pop-up appears in the right console, indicating, "You have a duplicate name, would you like to remove the second one?"
   * If the user clicks the button "Yes", the duplicated name will be removed, and the warning will go away.
   * if the user chooses "No, keep that for me", then nothing changes, and remove the warning.

**Comment by amyjko** [comment]
Thanks @xmzeng00! Here's some feedback:

* Per the design wiki, proposals go in the issue text, not a comment. Please move your design idea to where "TBD" is listed in the issue body.
* The editor already shows underlines for duplicates and already have functionality for showing the warning about the duplicate names. (e.g., try the program `name, name: 1` and you'll see it). The only part of the design proposal that doesn't exist it the prompt and button to remove.
* I'm not sure its a good idea to remove the warning; there really is no case where duplicate names are needed or helpful

**Comment by JunnaC** [comment]
Hi Amy, not sure if you would get a notification on adding design specifications. Jessi, and I updated the design specification draft2 here yesterday. Thanks for your help :))

**Comment by amyjko** [comment]
I don't get notifications when you edit the issue. You should always tag and comment to get someone's attention in GitHub; that's the only way to generate a notification.

I'm a little unclear on what your draft 2 proposal is proposing. We already show a conflict when there are duplicate names. This issue is about allowing creators to resolve the conflict by clicking a button to remove the name. Your proposal seems to be redundant with the conflict message already shown. Can you clarify?

**Comment by xmzeng00** [comment]
Hey Amy, we have updated the design spec! Can you take a look at it?
We are also considering the case that users may want to keep the duplicate names in languages for the purpose of international development collaboration. Is this something we should also consider, or say there's no such case?

**Comment by amyjko** [comment]
Thanks for the design proposal @xmzeng00! A bit of feedback:

* There's some good design exploration here!
* I don't think we need the note explaining that duplicate names are not helpful. Do you think this is important to explain?
* I think it would be reasonable to not warn when there are duplicate names with different language tags. They really are different names, since they have different metadata. Let's just not worry about that case.

**Comment by xmzeng00** [comment]
Hi Amy, thank you for your feedback! Relevant changes have been made to the post.
* For the note explaining that duplicate names are not helpful, we thought there might be some reason that the user would put a duplicate name if that happened (other than an accident), so it could be one thing to note and be alarmed, but we are open to remove that as well!
* And design for duplicate names with different language tags has been removed.

**Comment by amyjko** [comment]
Okay, I'm marking this buildable. Congrats on the approved design!

**Comment by amyjko** [comment]
It's the end of Winter! Please provide an update on this issue, including:

* Whether you plan to continue work on it
* If you do not, 1) provide a detailed update of its status, 2) add any unfinished work, 3) list any any unmerged branches, and 4) unassign yourself, so someone else can take over the task. Please leave the issue in better shape than you found it, helping future contributors to start from where you left off.

If you do plan to continue work on it, carry on. Otherwise, thank you for your contributions!

**Comment by JunnaC** [comment]
I will continue to work on it!

**Comment by amyjko** [comment]
No reply from @xmzeng00, unassigning.

**Comment by Txzho** [comment]
Hi, Amy! Could you give me some pointers on how to implement the design proposal?

**Comment by amyjko** [comment]
Yep! The key concept to understand is that the the `Conflict` type (defined in `Conflict.ts`) has a function `getConflictingNodes` that can optionally return a list of `Resolution`, each a little object that has a description of the resolution and function that returns a revised `Project` that resolves the conflict. The `DuplicateName` conflict (defined in `DuplicateName.ts`) just means that a `Bind` has multiple names that are the same, so a `Resolution` might be returned that replaces the original `Bind` with a `Bind` that does not have the duplicate name.

The files to modify for this would be:

- [ ] Revise `DuplicateName.ts` to return a `Resolution` that revises the project
- [ ] Update `NodeTexts.ts` `node > Bind > conflict > DuplicateName` to define a description of the resolution, per the design
- [ ] Add placeholders for all supported locales (`en-US.json`, `es-MX.json`, `zh-CN.json`) and the template `example.json`)
- [ ] Manually test it all to make sure it works for a few cases
- [ ] Submit a PR with the changes.

**Comment by euouae682** [comment]
Hi Amy! Thank you for the pointers! We've fixed and tested the issue for the case where a declaration has a duplicate name (or more than one duplicate name). However, we were confused about the case when there are duplicate names on separate lines, like in the following image:
![Capture1](https://github.com/wordplaydev/wordplay/assets/75504724/70969798-1b34-47b8-a670-3b83e56d6226)
We didn't see anything about this in the design specification, so we wanted to know whether this is included in the scope of this issue. Should there be a conflict resolution for this case as well?

**Comment by amyjko** [comment]
Ah, good catch; this issue was really about a single bind expression with duplicate names. The case of two separate bind statements can't really be resolved automatically, since there's no way to fix it without the creator making a decision about which one to keep. So consider that out of scope.

You mentioned that you implemented this, but I don't see a pull request for this issue. If you're ready for review, submit a PR.
