### ISSUE TITLE
Resolve unknown name

### ISSUE THREAD

**Issue by amyjko** [wordplaydev/wordplay#335]
## What's the problem?

When a name is unknown, but just a typo, it is often hard to notice why the name is unknown

`
number: 1
numbe + number
`

## What's the design idea?

Add a conflict resolution for `UnknownName`, offering to change the name to names that have a Levenstein distance of 1.

## Who benefits?

Anyone looking for a quick fix to the problem.

## Design specification

TBD

**Comment by amyjko** [comment]
It's the end of Winter! Please provide an update on this issue, including:

* Whether you plan to continue work on it
* If you do not, 1) provide a detailed update of its status, 2) add any unfinished work, 3) list any any unmerged branches, and 4) unassign yourself, so someone else can take over the task. Please leave the issue in better shape than you found it, helping future contributors to start from where you left off.

If you do plan to continue work on it, carry on. Otherwise, thank you for your contributions!

**Comment by amyjko** [comment]
No reply :( Unassigning @starter821 @eunjiii-2029344 @choKaylee.

**Comment by tsutari** [comment]
Hey @amyjko I'd like to request to be assigned to this issue.

**Comment by siddaay** [comment]
Hey @amyjko I'd like to request to be assigned to this issue

**Comment by amyjko** [comment]
@tsutari @siddaay Both of you asked for this so I've assigned both of you. You should collaborate on this work. If you're not willing to collaborate, figure out who's taking it and let me now.

A few notes about this:

* This is partially implemented already, but not using Levenstein distance. See what `UnknownName` does; it pulls all names in scope and recommends them, which isn't very precise.
* The design work to do here is minimal. It's mostly to decide things like 1) should the distance be 1 or also 2, to account for multiple typos?, 2) how should they be sorted?, 3) what should be recommended if nothing matches?

**Comment by siddaay** [comment]
Hi @amyjko, we felt good about our current implementation but realized our commits have been failing the "Deploy to Firebase Hosting on merge" test. We're a bit stumped on this as it doesn't seem related to the file we worked on, and were hoping for some guidance.
Here's a screenshot: 
![image](https://github.com/user-attachments/assets/39fc7dce-5180-43ff-9187-c87ccf9cb6d6)
 And our fork, if that may be helpful:
 https://github.com/siddaay/wordplay

**Comment by amyjko** [comment]
Ah, this is because the GitHub Action that deploys to a Firebase staging environment is running in your fork, but without any Firebase credentials to deploy with. You can safely ignore this; there's no need to deploy. You can disable all workflows for your fork as noted here:

https://github.com/orgs/community/discussions/26704

Most of the workflows we have set up are quality control gates (running tests, type checking), but you can do those locally and they are also enforced before a PR can be merged into `main`, so disabling it is fine.

**Comment by siddaay** [comment]
Sounds good, thank you! Will get started on the PR then.

**Comment by amyjko** [comment]
Once a quarter, I check each assignment to check the plans of the people that are assigned an issue. Please reply and indicate whether you intend to continue work on this issue. If you do not, please assign assign yourself, so we have an accurate account of who is working on an issue.

**Comment by siddaay** [comment]
I will not be working on this issue further. The issue is mostly resolved by #623 but there are some different design decisions that could be made with regards to the implementation which I included in the PR.

**Comment by amyjko** [comment]
I think I'm going to count this as resolved; (I overlooked the lack of an issue link on the PR, which would have auto-closed this).
