### ISSUE TITLE
Faulty Italic and Underline buttons/shortcuts

### ISSUE THREAD

**Issue by brightuw** [wordplaydev/wordplay#340]
## Expected behavior

When a **portion** of Phrase is already formatted and any of the toggles (italics, underline) are toggled on and off, it should repeat markup and un-markup the entirety of the Phrase.

## Actual behavior

When a **portion** of Phrase is already formatted (this feature works fine when the entire Phrase is marked up) with any markup tool (tested with weight, italics, and underline), when any of the toggles (italics, underline) are toggled on and off, it just adds a bunch of /'s or _'s without removing when untoggled.

Steps to see the defect:

1. Open any project
2. Create a Phrase with. Ex. ```Phrase(`text here`)```
3. Markup only a **portion** of the Phrase. Ex. ```Phrase(`*text* here`)```
4. Repeatedly toggle the underline and italics buttons and see the excess /'s and _'s

## Screenshots

![The text "text here" with only the word, "text" bolded, before toggling any of the markup buttons](https://github.com/wordplaydev/wordplay/assets/114948317/ece1d5aa-264d-4be3-82ef-9b417e26d319)
#### Figure 1. Partially formatted text before toggling any markup shortcuts/buttons.

![The original "text here" texting has four slashes before and after the text](https://github.com/wordplaydev/wordplay/assets/114948317/8d9f05a8-a39a-4c33-826e-4cb41e06158a)
#### Figure 2. That same text, but the italics button was toggled 8 times.

![The previous "text here" with previous slashes but also 2 underscores before and after the text](https://github.com/wordplaydev/wordplay/assets/114948317/064fd04e-781e-46bf-82e4-0d280263978b)
## Environment

Desktop

Directly on Wordplay.dev
-   OS + version: Windows 11 Home, Version 22H2, OS Build 22621.2861
-   Browser + version: Google Chrome Version 120.0.6099.131 (Official Build) (64-bit)

**Comment by amyjko** [comment]
Thanks for reporting! It looks like there's an edge case I missed. I caused this, I'll fix it.

**Comment by brightuw** [comment]
Sorry to pester about this issue again but the issue persists. Specifically, if you go to Learn > Take the stage > Phrase > Slide 8, and start spamming the italics button, the problem will show itself surrounding the Phrase with //// before and after again.

**Comment by amyjko** [comment]
Pestering is good! We want things to work, and your attention to detail on this is an asset. I'll take another look.

**Comment by amyjko** [comment]
Okay, I'm now 99% confident I've resolved all of the edge cases. As part of the latest fix, I also provided better visual feedback on checkboxes for mixed formatting.
