### ISSUE TITLE
Redundant keys in maps should use last value to evaluate

### ISSUE THREAD

**Issue by kelliannr** [wordplaydev/wordplay#341]
## Expected behavior

The value for the 'ben' key should be "5points" since that value is the most recent one.

## Actual behavior

In Mappings 7/13, the visual representation of the map on the stage displays "2points", which contradicts what the first speech bubble on the left side says ("this gives me two keys, but I just use the last one.")

Steps to get to issue:

1. Go to 'Learn' page
2. Click on 'Mappings' under the 'Ensembles' section of the dropdown next to 'Learn'
3. Click through tutorial until the subtitle heading says 'Mappings 7/13'

## Screenshots

![Screenshot 2024-01-10 at 10 54 02 PM (2)](https://github.com/wordplaydev/wordplay/assets/73355041/0d56d8ea-892b-4498-ab32-3c6e7a2279f5)

## Environment

Apple Macbook Air, Sonoma 14.1, Chrome Version 120.0.6099.199

**Comment by amyjko** [comment]
Thanks for reporting! I'll assign myself on this one; it's a defect in the programming language implementation.
