### ISSUE TITLE
Feedback when email account does not exist

### ISSUE THREAD

**Issue by YizhouDing** [wordplaydev/wordplay#343]
# Feedback when email account does not exist

Erica Ding

## Problem

At present, Wordplay has chosen to provide the option of logging in only with a Wordplay account due to user privacy concerns. However, there are still users who have registered using their email addresses. The main goal of this design is to provide notifications when there is no account linked to an email.

### 1. Legacy email-only account explanation

As some users continue to use email account logins, we understand that this login method may cause confusion for others. To address this, there is a small question mark icon next to the email account login option. When users click on this icon, a brief explanation about legacy email-only accounts will appear. This feature aims to reduce user confusion and provide clarity regarding the email login option.

<img width="975" alt="explanation" src="https://github.com/wordplaydev/wordplay/assets/108030139/f8e213f4-4070-4b45-843d-b39dbe983e94">

### 2. User Feedback Feature

Consider implementing a more interactive feedback system that can guide users through troubleshooting steps without revealing sensitive information. For example, if a user attempts to log in and the account does not exist, the system could suggest steps like checking for typographical errors in the email address, trying a different email address, or guiding them to sign up for a new account if they are new users.

<img width="800" alt="pop up message" src="https://github.com/wordplaydev/wordplay/assets/108030139/b61a4b5f-fc17-4a07-984e-2f2e17321c18">

If that is possible, Implementing a CAPTCHA verification step before showing the feedback message could also deter automated bots from trying to discover valid email accounts.

However, since most of Wordplay email legacy users are Wordplay contributors, we are also conducting user testing sessions. Collect feedback on the proposed features to ensure they are intuitive and helpful. Adjustments based on real user interactions can significantly enhance the effectiveness of the solution.

**Comment by amyjko** [comment]
@YizhouDing Please include your Chrome version in the description.

Also, are you sure you previously created a Wordplay account with the email address `yding25@uw.edu`? I don't see an account with that address in the database. (If you didn't, that's why you wouldn't receive an email).

**Comment by YizhouDing** [comment]
> @YizhouDing Please include your Chrome version in the description.
> 
> Also, are you sure you previously created a Wordplay account with the email address `yding25@uw.edu`? I don't see an account with that address in the database. (If you didn't, that's why you wouldn't receive an email).


I've included my Chrome version in the description. I also tried "dingyizhou1104@hotmail.com" as a possible login email for the account, but I also didn't get a sign-in email. If the email address "dingyizhou1104@hotmail.com" is not displayed in the database, I was probably unsuccessful in creating an account before.

**Comment by amyjko** [comment]
There's also no account associated with `dingyizhou1104@hotmail.com`. That means that you never had an email-based account.

That said, I think this is still a usability issue. We should be providing feedback when an account isn't associated with an email. This is in tension with authentication best practices, which generally involve _not_ disclosing whether an account exists, to make it harder to try to overtake someone's account. So there's a decision here to make about whether to prioritize usability or security.

**Comment by YizhouDing** [comment]
That makes sense. Shall I delete this issue then?

On Jan 12, 2024, at 12:02 PM, Amy J. Ko ***@***.***> wrote:

﻿

There's also no account associated with ***@***.*** That means that you never had an email-based account.

That said, I think this is still a usability issue. We should be providing feedback when an account isn't associated with an email. This is in tension with authentication best practices, which generally involve not disclosing whether an account exists, to make it harder to try to overtake someone's account. So there's a decision here to make about whether to prioritize usability or security.

**Comment by amyjko** [comment]
No need to delete; there's still a design change to make here, if we decide to provide feedback about no account being associated with an email.

**Comment by YizhouDing** [comment]
Ok sure! I can keep working on design that UI.

On Jan 12, 2024, at 12:49 PM, Amy J. Ko ***@***.***> wrote:

﻿

No need to delete; there's still a design change to make here, if we decide to provide feedback about no account being associated with an email.

**Comment by amyjko** [comment]
If you're offering to work on this as a designer, assign yourself, then follow the steps on the design wiki. (Otherwise, I've assigned myself by default as designer and developer).

The key design issue here is whether to break security best practices.

**Comment by YizhouDing** [comment]
# Feedback when email account does not exist

Erica Ding


## Problem

At present, Wordplay has chosen to provide the option of logging in only with a Wordplay account due to user privacy concerns. However, there are still users who have registered using their email addresses. The main goal of this design is to provide notifications when there is no account linked to an email.

## Proposed Solution

### 1. Legacy email-only account explanation

As some users continue to use email account logins, we understand that this login method may cause confusion for others. To address this, there is a small question mark icon next to the email account login option. When users click on this icon, a brief explanation about legacy email-only accounts will appear. This feature aims to reduce user confusion and provide clarity regarding the email login option.

<img width="975" alt="explanation" src="https://github.com/wordplaydev/wordplay/assets/108030139/f8e213f4-4070-4b45-843d-b39dbe983e94">


### 2. User Feedback Feature

When a user attempts to log in using their email, they can enter their email address and click the sending button. Developers could implement a feature that, upon clicking the sending button, checks our database to determine if an email account is stored there. If a matching email account is found, a pop-up message will appear saying, 'You have a legacy email-only account, and you will receive a login link.' If no matching email account is found, a pop-up message will appear saying, 'Sorry, you do not have a legacy email-only account; please create a new one.' This ensures that users will not be confused about the existence of legacy email-only accounts.

<img width="798" alt="have a email account pop-up" src="https://github.com/wordplaydev/wordplay/assets/108030139/0b857cd0-4924-42b1-bc9c-e032423f01b9">

<img width="820" alt="do not have a email account pop-up" src="https://github.com/wordplaydev/wordplay/assets/108030139/769f1d81-5744-4280-889b-89e527ec8eeb">

**Comment by YizhouDing** [comment]
@amyjko Hi Amy, I finish the design for this feedback UI design. Please let me know if the design needs other improvements.

**Comment by amyjko** [comment]
Hello @YizhouDing! Nice start. Feedback:

* Per the design process described in the wiki, design specifications go in the main issue text in a "Design Proposal" section, not in a comment. Please move the design proposal there instead of the comment.
* This design exposes that the email address is in use, and could therefore be used to identify users that have accounts on the site. It could also be used to enumerate accounts. We may enable Firebase's [email enumeration](https://cloud.google.com/identity-platform/docs/admin/email-enumeration-protection) feature to prevent this attack, which would mean that we would no longer be able to know whether the account exists, and no longer be able to provide feedback about whether an email will be sent. This design needs to work around that constraint, where we can't give feedback about whether an email will be sent.

**Comment by YizhouDing** [comment]
Hi Amy, I revised the proposal after paying consideration to the user's experience and data security. please take a look and let me know if is there anything else I could work on for this issue. @amyjko

**Comment by amyjko** [comment]
Thanks @YizhouDing! I think this is ready to build. Design approved!

**Comment by YizhouDing** [comment]
> Thanks @YizhouDing! I think this is ready to build. Design approved! Would you like to act as developer? If not, you can unassign yourself, so everyone knows it's available to assign.

Thank you for help! I just unassigned

**Comment by amyjko** [comment]
Okay, sounds good! Thanks for the design work on this. I'll see if I can implement soon.
