### ISSUE TITLE
Unable to locate GCLOUD_PROJECT:-template file on windows computers

### ISSUE THREAD

**Issue by meepsterleapster** [wordplaydev/wordplay#359]
## Expected behavior

Program would be able to locate the file on a Windows OS and successfully run npm run build

## Actual behavior

1. In terminal run  'npm run build' 
2. See error below

## Screenshots

<img width="296" alt="image" src="https://github.com/wordplaydev/wordplay/assets/155786514/ec9a54eb-127b-4dc7-a38a-ef5e114f2f81">

## Environment

Desktop

-   OS + version: Windows 11 (Version 22H2 OS Build 22621.3007)
-   Browser + version:  N/A

-  Visual Studio Code, terminal

**Comment by meepsterleapster** [comment]
Additionally, running 'ls' in terminal shows .env files do exist on one's own end

**Comment by amyjko** [comment]
Thanks @meepsterleapster, I'll investigate and resolve this one soon.
