### ISSUE TITLE
Faulty Scrollbar

### ISSUE THREAD

**Issue by RuweydaAbdi** [wordplaydev/wordplay#361]
## Expected behavior

The scrollbar should work so that the user is able to scroll down, and see all the languages, (even the languages that have not been added yet). When a "pop up" menu appears (beta, language menu, settings, ect) Notice how if you click outside the menu, the menu would disappear. This part is intended. when you click inside the menu, the user is able to interact within its contents. That is also intended. 

## Actual behavior

However when you click onto "English" on the main toolbar to choose your language (bottom of page). The scrollbar does not allow the user to click onto it without the language menu disappearing. As you click the scrollbar, or to a point near the scrollbar. It seems like there is an error in its code where that part of the menu is considered "outside". The issue goes beyond the scrollbar (Though mostly affects the scrollbar), and the menus to a point a little away from the end, is considered “outside” and makes it disappear.

## Screenshots

<img width="958" alt="image" src="https://github.com/wordplaydev/wordplay/assets/146573912/574a7871-feb8-4a36-ba71-d5852281709f">

## Environment

I am using an ASUS vivobook S14 Flip, Windows 11. Chrome browser, OS- 22621.3007, Version: 22H2 , Processor: AMD Ryzen 5 5600H with Radeon Graphics, 3.30 GHz

My laptop has a Touchscreen. When I use my hands, the scrollbar works fine. This may be an issue depending on the device.

**Comment by amyjko** [comment]
Thanks @RuweydaAbdi! Please use the required bug report template for this; all of the headers in the template are there for a reason and shouldn't be deleted.

**Comment by RuweydaAbdi** [comment]
Will do!

**Comment by amyjko** [comment]
Thanks! This is much better.
