### ISSUE TITLE
Clarification in Verify Wiki Page

### ISSUE THREAD

**Issue by meepsterleapster** [wordplaydev/wordplay#372]
##The problem?

On the the Verify role page (https://github.com/wordplaydev/wordplay/wiki/verify) under guideline #2 it currently says:

"Once you've chosen a unit or end-to-end, research what tests we already have for the unit or activity. Our unit tests end with the .test.ts extension in the repository. Our end-to-end tests our stored in /tests."

The slight problem with this is that end2end tests using playwright in the /tests folder also need to be titled .test.ts just like unit tests
## What's the design idea?

Modify the language to suggest that "Both unit tests and end-to-end tests must end their files with .test.ts in order to be considered tests within the system. Additionally end-to-end need to be stored in the /tests directory as well.
## Who benefits?

People who do verification work, understanding end-to-end tests must also follow the unit-test guidelines make sense, but might not be inherently obvious to newcomers to the project.

## Design specification

(This section should be included after a design proposal is ready and approved, and the `buildable` tag is added. This text can remain until then. Designers should add their proposal here, not in a comment).

**Comment by amyjko** [comment]
Thanks for reporting! I just updated the wiki with this recommendation.
