### ISSUE TITLE
Unable to delete a placeholder immediately

### ISSUE THREAD

**Issue by mmk49** [wordplaydev/wordplay#374]
## Expected behavior

I delete some number in a statement and it replaces the number with a placeholder. I want to be able to delete the placeholder immediately after I delete some number. This should intuitively require two clicks of the backspace after I select some number in a statement.

## Actual behavior

For this issue, imagine that you are in the scenario where you have just typed "1 + 2" into the code editor. You meant to type something else besides the 2 so you select it and attempt to delete it. You are able to delete the 2 but then you are met with a placeholder. You then attempt the placeholder because you do not want it there. However, you realize that you are unable to delete the place holder unless you arrow over to the left or the right. Instead, you should be able to delete the placeholder immediately instead of having to arrow over to the left or the right.

## Screenshots

I will explain the actual behavior through screenshots as well. Here is our case:
![ErrorImg1](https://github.com/wordplaydev/wordplay/assets/114621124/d24f81f5-b546-4b57-a3d8-a70009a97dd3)

I have selected the 2 because I meant to type something else
![ErrorImg2](https://github.com/wordplaydev/wordplay/assets/114621124/6b51b6ae-723e-44ef-bef8-e6540d9425f5)

I have deleted the two that I selected and it has been replaced by a placeholder value (notice how the cursor is in the middle). At this point I would hope that I can just delete the placeholder immediately but I am forced to arrow to the right first
![ErrorImg3](https://github.com/wordplaydev/wordplay/assets/114621124/f153359b-c26d-489a-88c6-9354c3fed5e2)

I have now arrowed to the right (notice how the cursor is to the right). Now I am able to delete the placeholder, but this is unintuitive. I would rather have it that I can delete the placeholder immediately
![ErrorImg4](https://github.com/wordplaydev/wordplay/assets/114621124/af0fc3bc-d181-4082-8bf0-bbca7c5dbe60)

I finally deleted the number! Now I can type something besides the 2.
![ErrorImg5](https://github.com/wordplaydev/wordplay/assets/114621124/08c6d182-15d0-4c2d-9db6-25a351829126)

## Environment

Desktop

-   Windows 10 Home + Version 10.0.19045 Build 19045
-   Google Chrome + Version 121.0.6167.140 (Official Build) (64-bit)

**Comment by amyjko** [comment]
Thanks @mmk49, I'll fix this one!
