### ISSUE TITLE
Mix-up and wrong usages of referring to director, and characters in the Verse as "person" or "people" in simplified Chinese tutorial

### ISSUE THREAD

**Issue by tianhuizhou73** [wordplaydev/wordplay#375]
## Expected behavior

Translation of "person" to Chinese when referring to the director should be uniform and make sense in Chinese.
Translation of the characters in the Verse should not refer to them as "people" at all due to plot point in the tutorial of them needing people to give meaning.

## Actual behavior

Unorthodox translations of "person" when referring to the director throughout the Chinese locale such as “人类”.
Characters in the Verse often referred to as "people" either directly as "人" or indirectly such as "其他的人" in strange ways. 

## Screenshots

N/A, Happens throughout Chinese locale.

## Environment

N/A. In chinese-simplified branch.

**Comment by awang040403** [comment]
Hi @amyjko, could you please assign me to this issue?

**Comment by amyjko** [comment]
Once a quarter, I check each assignment to check the plans of the people that are assigned an issue. Please reply and indicate whether you intend to continue work on this issue. If you do not, please assign assign yourself, so we have an accurate account of who is working on an issue.

**Comment by awang040403** [comment]
Hi @amyjko, I have solved the issue and submitted a reviewed pull request. Could you please close it? Thanks!

**Comment by amyjko** [comment]
Resolved by previous PR.
