### ISSUE TITLE
Not uniform pronouns for referring to director in simplified Chinese tutorial.

### ISSUE THREAD

**Issue by tianhuizhou73** [wordplaydev/wordplay#376]
## Expected behavior

Uniform pronouns for referring to director, in third-person or in second-person "you", in Chinese tutorial.

## Actual behavior

“你” and “您” and “他” and “她” (you, more respectful you, he, she) are all used in the Chinese tutorial to refer to the director. Sometimes he/she avoided too obviously to avert this issue and becomes awkward.

## Screenshots

N/A, Happens throughout simplified Chinese tutorial.

## Environment

N/A. Throughout simplified-chinese branch.

**Comment by tianhuizhou73** [comment]
Could possibly use "Ta" to avoid he/she but this uses english letters.

**Comment by awang040403** [comment]
Hi @amyjko, could you please assign me to this issue?

**Comment by amyjko** [comment]
Sure! Assigned.

**Comment by amyjko** [comment]
Once a quarter, I check each assignment to check the plans of the people that are assigned an issue. Please reply and indicate whether you intend to continue work on this issue. If you do not, please assign assign yourself, so we have an accurate account of who is working on an issue.

**Comment by awang040403** [comment]
Hi @amyjko, I have solved the issue and submitted a reviewed pull request. Could you please close it, thank you?

**Comment by amyjko** [comment]
Ah, this was just missing a link to the PR. Thanks.
