### ISSUE TITLE
A more compelling home page

### ISSUE THREAD

**Issue by amyjko** [wordplaydev/wordplay#397]
## What's the problem?

The current home page is adequate, providing direct access to areas of the platform and communicating at a high level what the platform is. However, it is not particularly compelling:

* It doesn't convey what kind of content can be created
* It doesn't convey the justice-centered mission of the project
* It doesn't convey who the site is intended for (learners and their teachers)
* It doesn't convey what is unique about the language and platform

### Verbal: 

- "The sentence is too long for me to read, even though there are emojis but I still don't want to read"  -> Solution: Making the sentence eye catching and reducing long sentences
- "I am only reading the extra large text"

### Accessible:

- Make "help" and "language" more visible  -> solution: using this icon <img width="20" alt="global language icon " src="https://github.com/wordplaydev/wordplay/assets/108030139/fb51fd9c-947d-4d66-889d-9c1af5c72ca5"> instead of “English”, “中文”，“Espanol”

- Looks like a chat button <img width="200" alt="Screen Shot 2024-03-03 at 11 32 08 PM" src="https://github.com/wordplaydev/wordplay/assets/108030139/719f8908-ded2-4e51-9b5d-9d9af384f4dc">
-> Solution: 1. maybe we can use our old version mascot instead of chat bubble? 2. Make chat bubble logo another outstanding color and also make it larger

### layout : 
- Nav bar on top will be better
- No scrolling, be on 1 page
- Why the words are different size
<img width="200" alt="words in different sizes" src="https://github.com/wordplaydev/wordplay/assets/108030139/58421410-1bd6-491c-a99a-60a8797769e1">

### pattern:

- The floating letters are hard to see
- I prefer the little cute speech bubble, the mascot before-> Solution: it is more memorable in a marketing way
- It would be better if the words were icons - related to emojis -> Solution: we can find related emojis, since we use a lot of emojis in Wordplay
- Colorful 

If it were more compelling, more of our target audience might try it.

## What's the design idea?

One concept to consider is something that better aligns with marketing standards for landing pages:

* A clear value proposition
* A "hero shot", which might be something that conveys what can be created with the platform
* Features and benefits relative to competitors
* Social proof of who is using it
* A call to action

### Design specification
Designer: Erica Ding
#### 1. Homepage Narrative Enhancement
To streamline communication and captivate users from the outset, we propose refining the homepage narrative into succinct bullet points. These bullet points, accompanied by emojis, will effectively convey Wordplay's key features, such as animating words and emojis, fun learning activities, multi-language support, and content sharing capabilities. By integrating emojis, we aim to enhance readability and engagement, fostering a connection with our audience.

Here are the proposed verbal texts: 
Hero shot: Create stories using words and symbols from your language and your abilities!
🖥︎️Wordplay is a cool programming language that allows you to:

- 😃Animate Words and Emojis: Explore the exciting opportunity to learn coding by bringing words, emojis, and symbols to life, fostering creativity while honing problem-solving skills.
- 🎲Fun Features: Wordplay provides a dynamic and inclusive learning environment where students can explore coding in a fun and educational way.
- 🔑Languages and Accessibility: Enjoy multi-language support and easy communication between students and teachers. With comprehensive documentation and adherence to accessibility standards, Wordplay ensures a safe and supportive space for learning and collaboration.
- 🤝‍Share Your Creations: Showcase your creations by sharing them with friends, groups, or anyone around the world!
- 🆓Totally Free: Access all features for free, free forever from University of Washington Information School!

I'm utilizing the narrative provided on our homepage, transforming it into bullet points and integrating emojis for enhanced readability. The hero shot aims to engage students with clear communication, while the following paragraph delves into more detailed information for teachers about our platform.

<img width="546" alt="suggested homepage texts" src="https://github.com/wordplaydev/wordplay/assets/108030139/0a6f9d6c-63d5-4f1b-90b5-393131095272">

#### 2. Language Icon Integration

In adherence to web standards and our commitment to inclusivity, we recommend incorporating a language icon on the platform. This icon will symbolize our support for linguistic diversity and accessibility, ensuring that users feel welcomed and represented regardless of their language or cultural background. This icon would be placed at the footer.
<img width="158" alt="icon" src="https://github.com/wordplaydev/wordplay/assets/108030139/575e83ef-4ad7-4b9c-80fa-4e0f42183e02">

<img width="587" alt="icon placed at footer" src="https://github.com/wordplaydev/wordplay/assets/108030139/6011ba4c-e103-449c-a56f-32fae9d8ed85">

#### 3. Navigation Bar Optimization
After careful consideration of user navigation patterns and privacy concerns, we propose retaining the navigation bar on the homepage. However, to balance usability with privacy, we suggest implementing a feature that redirects users to the login page upon clicking on specific sections like "learn," "projects," or "galleries." This approach will provide users with essential information about our login system while safeguarding their privacy and data integrity.

#### 4. Homepage Block Organization
To optimize the homepage layout and improve user engagement, we recommend organizing content into visually appealing blocks. These blocks, comprising sections such as "learn," "projects," and "galleries," will serve as focal points for users, facilitating intuitive navigation and highlighting key platform features. Additionally, the inclusion of emojis before titles will inject a playful element into the interface, enhancing user experience and retention.

Building upon existing design elements, we propose aligning the homepage layout with the motif of our account profile page. By introducing an additional block, we aim to achieve visual symmetry and balance, thereby reducing the need for excessive scrolling on smaller screens. The proposed layout enhancements will not only improve the platform's visual appeal but also enhance usability and accessibility for all users.

<img width="546" alt="suggested homepage design"
 src="https://github.com/wordplaydev/wordplay/assets/108030139/0a6f9d6c-63d5-4f1b-90b5-393131095272">

<img width="546" alt="highlighted when hover" src="https://github.com/wordplaydev/wordplay/assets/108030139/bb1ecc22-0f7a-4ddf-be6b-e82a84a24dee">

#### 5. Optimized for mobile and web use, and designed to facilitate future iterations

The homepage for large screens has been redesigned, along with corresponding adaptations for medium and small screens. A new footer has been added to the homepage, organizing additional information in a clearer layout to enhance user accessibility.

The login feature has been repositioned below the introduction to Wordplay to ensure users authenticate before accessing the coding features. To accommodate this expansion, the Login has been repositioned above the panels, ensuring that it remains easily accessible, regardless of the number of future panel additions.

For the small screen, the gray boxes will have a wider width(as shown in the screenshot)
<img width="180" alt="home page small screen" src="https://github.com/wordplaydev/wordplay/assets/108030139/c5818b0b-031e-4d47-a64e-292069a2aaa0">

For the medium screen, it has smaller boxes than the large screen
<img width="300" alt="home screen medium screen" src="https://github.com/wordplaydev/wordplay/assets/108030139/7bb56301-a4b8-48a2-af9e-439bb246f272">

For the large screen, enlarge the box sizes
<img width="600" alt="larger screen"
 src="https://github.com/wordplaydev/wordplay/assets/108030139/0a6f9d6c-63d5-4f1b-90b5-393131095272">

**Comment by amyjko** [comment]
@YizhouDing, I see you assigned yourself to this. Are you wanting to work on it as a designer? Remember, according to our workflow, when you assign yourself, you need to write a comment so people know what your self-assignment means. Thanks!

**Comment by YizhouDing** [comment]
> @YizhouDing, I see you assigned yourself to this. Are you wanting to work on it as a designer? Remember, according to our workflow, when you assign yourself, you need to write a comment so people know what your self-assignment means. Thanks!

Yes, I want to work on it as a designer. Thanks for reminding me that.

**Comment by amyjko** [comment]
Okay, thanks for confirming. Let me know if I can elaborate on any of the goals in the design idea; the key thing to think about is our two stakeholders: 6th grade students and their teachers. This is really more of a marketing issue than a design issue, but they overlap enough that it's okay to think about it as design.

**Comment by YizhouDing** [comment]
@amyjko Hi Amy, I put user feedback in this Google doc, and also added some of my thoughts. Please take a look, let me know if there is any idea I need to explain or improve. https://docs.google.com/document/d/1dywDIRd63zct2qUnQTwDHdOszKqfsatvlXwd5CgitXE/edit?usp=sharing

**Comment by amyjko** [comment]
@YizhouDing Per the [design guidelines in the wiki](https://github.com/wordplaydev/wordplay/wiki/design#propose-designs), please don't link to external sources; keep everything in GitHub, so we have the full context for conversations. Please repost your thoughts as a comment instead of a link, and then I'll reply. If the thoughts are a design proposal, then put your design proposal in the issue body, per the wiki.

Sorry to be pedantic about process: I have to think about future quarters, dead links, and newcomers, and that's what our guidelines try to account for. Thanks!

**Comment by YizhouDing** [comment]
Consider: “Why should I use this?”, what is the pain point

# User test and user feedback: 
## Verbal: 

- "The sentence is too long for me to read, even though there are emojis but I still don't want to read"  -> Solution: Making the sentence eye catching and reducing long sentences
- "I am only reading the extra large text"

## Accessible:

- Make "help" and "language" more visible  -> solution: using this icon <img width="20" alt="global language icon " src="https://github.com/wordplaydev/wordplay/assets/108030139/fb51fd9c-947d-4d66-889d-9c1af5c72ca5"> instead of “English”, “中文”，“Espanol”

- Looks like a chat button <img width="200" alt="Screen Shot 2024-03-03 at 11 32 08 PM" src="https://github.com/wordplaydev/wordplay/assets/108030139/719f8908-ded2-4e51-9b5d-9d9af384f4dc">
-> Solution: 1. maybe we can use our old version mascot instead of chat bubble? 2. Make chat bubble logo another outstanding color and also make it larger

## layout : 
- Nav bar on top will be better
- No scrolling, be on 1 page
- Why the words are different size
<img width="200" alt="words in different sizes" src="https://github.com/wordplaydev/wordplay/assets/108030139/58421410-1bd6-491c-a99a-60a8797769e1">


## pattern:

- The floating letters are hard to see
- I prefer the little cute speech bubble, the mascot before-> Solution: it is more memorable in a marketing way
- It would be better if the words were icons - related to emojis -> Solution: we can find related emojis, since we use a lot of emojis in Wordplay
- Colorful

**Comment by YizhouDing** [comment]
> @YizhouDing Per the [design guidelines in the wiki](https://github.com/wordplaydev/wordplay/wiki/design#propose-designs), please don't link to external sources; keep everything in GitHub, so we have the full context for conversations. Please repost your thoughts as a comment instead of a link, and then I'll reply. If the thoughts are a design proposal, then put your design proposal in the issue body, per the wiki.
> 
> Sorry to be pedantic about process: I have to think about future quarters, dead links, and newcomers, and that's what our guidelines try to account for. Thanks!

I understand the importance of keeping everything within GitHub for clarity and accessibility. My apologies for not adhering to the guidelines initially. I've already converted the content into Markdown format and added it as a comment. Let me know if there's anything else needed!

**Comment by amyjko** [comment]
Thanks @YizhouDing. Also remember that design proposals belong in the issue body, not in a comment. Put problems you found in research in the  "What's the problem?" section, and design proposals in the design specification section. This keeps everything organized, so people don't have to read the comment history to make sense of the problem and proposal. (And in general, please read the design wiki carefully — we have the guidelines written there so you can refer to them while you work).

Thoughts on the findings in your informal user research:

* Students not wanting to read is something that has been deeply worrying me over the past few years. It's a noticeable change from 10 years ago, when students would willingly read long research papers I gave them; now they're resistant to reading a paragraph. I have no idea what to do about this; I don't want to feed into a culture that doesn't read, as reading is essential to learning. That said, we can find ways of organizing the messaging to make comprehension easier, so we should do that.

* Icons are not more accessible for creators who rely on screen readers. They are less accessible. And there is no standard icon for language settings, so there is no icon that would be recognized by everyone.

* The chat emoji is the icon for Wordplay; are you proposing to change the icon for the whole application? Or just proposing to use something different for the home link?

* Why would the nav bar on top be better?

* How would the design avoid scrolling on smaller screens?

I look forward to a more concrete design proposal. Think through these questions and we can discuss more here.

**Comment by YizhouDing** [comment]
Hi Amy, Here are the updates on the redesign from this week. Here are my responses to the questions you provided:

**- Students not wanting to read is something that has been deeply worrying me over the past few years. It's a noticeable change from 10 years ago, when students would willingly read long research papers I gave them; now they're resistant to reading a paragraph. I have no idea what to do about this; I don't want to feed into a culture that doesn't read, as reading is essential to learning. That said, we can find ways of organizing the messaging to make comprehension easier, so we should do that.**

I completely agree that reading is vital for students. Personally, as someone who struggles with reading, I find breaking paragraphs into bullet points helpful. However, I'm unsure if this format would suit our homepage.

**- Icons are not more accessible for creators who rely on screen readers. They are less accessible. And there is no standard icon for language settings, so there is no icon that would be recognized by everyone.**

I regret not being aware of it previously. Considering a national flag next to the language button could help non-English users recognize it as a language selection option.
<img width="150" alt="national flag next to language button" src="https://github.com/wordplaydev/wordplay/assets/108030139/4ab12588-96b5-4cf7-b13b-a3fd8dbbf9d4">

**- The chat emoji is the icon for Wordplay; are you proposing to change the icon for the whole application? Or just proposing to use something different for the home link?**

Could we create a unique icon specifically for our platform? One of our contributors suggested that having a distinct icon would make our platform more memorable. I am thinking about something like this:  
<img width="80" alt="new wordplay icon" src="https://github.com/wordplaydev/wordplay/assets/108030139/cb09b7ed-a24e-471a-9533-506aeffbfa03">

- **Why would the nav bar on top be better?**

According to the contributor who proposed this idea, she believed that placing the navigation bar on top would align with the common practice among most platforms, making it more familiar for our users. However, from my perspective, I don't believe it significantly impacts our platform. Regarding our login approach, do we intend for users to create an account/login before accessing our platform? If so, I would recommend removing the navigation bar from the homepage, allowing users to view the homepage first and then log in as prompted.

- **How would the design avoid scrolling on smaller screens?**

To avoid excessive scrolling on smaller screens, I redesigned the homepage to organize "learn," "projects," and "galleries" features into blocks. These blocks will draw users' attention and maintain organization. Additionally, I've added emojis before titles to add a playful element. Hovering over a block will highlight it in light yellow to indicate the user's focus.
<img width="741" alt="new wordplay homepage" src="https://github.com/wordplaydev/wordplay/assets/108030139/a0d75f43-2ee8-4de7-9b0d-3bc20366c731">

<img width="739" alt="new wordplay homepage - hover" src="https://github.com/wordplaydev/wordplay/assets/108030139/35f91ec7-01b8-4127-874f-6063a1cb7e5f">

Regarding the verbal displayed on the homepage, I'm still considering how to effectively communicate with both students and teachers. Please let me know if you have any questions about this week's updates. After your approval of any ideas, I'll incorporate them into the design proposal and design spec sections.

**Comment by YizhouDing** [comment]
@amyjko Hi Amy, based on the feedback you provided, I came up with the following design ideas.

**-Our narration on the homepage:**
### Hero shot: Create stories using words and symbols from your language and your abilities!
🖥︎️Wordplay is a cool programming language that allows you to:

- 😃Animate Words and Emojis: Explore the exciting opportunity to learn coding by bringing words, emojis, and symbols to life, fostering creativity while honing problem-solving skills.
- 🎲Fun Features: Wordplay provides a dynamic and inclusive learning environment where students can explore coding in a fun and educational way.
- 🔑Languages and Accessibility: Enjoy multi-language support and easy communication between students and teachers. With comprehensive documentation and adherence to accessibility standards, Wordplay ensures a safe and supportive space for learning and collaboration.
- 🤝‍Share Your Creations: Showcase your creations by sharing them with friends, groups, or anyone around the world!
- 🆓Totally Free: Access all features for free, free forever from University of Washington Information School!

I'm utilizing the narrative provided on our homepage, transforming it into bullet points and integrating emojis for enhanced readability. The hero shot aims to engage students with clear communication, while the following paragraph delves into more detailed information for teachers about our platform.

**-Language icon:**

Yes, we should definitely follow the web standard!
<img width="158" alt="Screen Shot 2024-03-12 at 6 24 31 PM" src="https://github.com/wordplaydev/wordplay/assets/108030139/575e83ef-4ad7-4b9c-80fa-4e0f42183e02">

**-Hiding footer:**
After considering the drawbacks of removing the navigation bar from the homepage, I believe it's best to retain it. However, we could implement a feature that redirects the user to the login page by clicking on "learn," "projects," or "galleries". This would provide them with additional information about our login system, allowing users to decide whether to log in. Such an approach would enhance users' awareness of privacy and security while also preventing data loss or incomplete assignments. For example, if users are using a school computer, this feature would ensure that they don't risk losing their unfinished assignments.

**-Blocks on the homepage:**
I was considering something similar previously, aligning with the layout of our account profile page. However, currently, we only have three blocks, resulting in an asymmetrical design. Adding another block would create a more balanced layout. Therefore, I believe the layout I suggested earlier not only enhances visual appeal but also avoids the need for scrolling.

(left image: same motif as profile page, right image: proposed homepage design
<img width="400" alt="same motif as profile page" src="https://github.com/wordplaydev/wordplay/assets/108030139/7d9552d3-ae94-410d-8bd2-dabe1091fc60"><img width="400" alt="last time proposed homepage design" src="https://github.com/wordplaydev/wordplay/assets/108030139/263cf330-e73a-4c8d-9249-029db3c02840">

**Comment by amyjko** [comment]
It's the end of Winter! Please provide an update on this issue, including:

* Whether you plan to continue work on it
* If you do not, 1) provide a detailed update of its status, 2) add any unfinished work, 3) list any any unmerged branches, and 4) unassign yourself, so someone else can take over the task. Please leave the issue in better shape than you found it, helping future contributors to start from where you left off.

If you do plan to continue work on it, carry on. Otherwise, thank you for your contributions!

**Comment by YizhouDing** [comment]
> It's the end of Winter! Please provide an update on this issue, including:
> 
> * Whether you plan to continue work on it
> * If you do not, 1) provide a detailed update of its status, 2) add any unfinished work, 3) list any any unmerged branches, and 4) unassign yourself, so someone else can take over the task. Please leave the issue in better shape than you found it, helping future contributors to start from where you left off.
> 
> If you do plan to continue work on it, carry on. Otherwise, thank you for your contributions!

Hi Amy, I will continue working on it till I'm done! Even though I won't be enrolled for credits next quarter, I'm still committed to volunteering and continuing the work.

**Comment by amyjko** [comment]
Thanks for the update @YizhouDing! I look forward to the next sketch.

**Comment by JunnaC** [comment]
Olivia and Junna(me) want to work on this issue and assign ourselves.

**Comment by YizhouDing** [comment]
@amyjko Hi Amy, I updated the design proposal for this issue. Please take a look and let me know is there anything else I need to do.

**Comment by YizhouDing** [comment]
> @YizhouDing You'll need to coordinate with @oliviawei1102 and @YizhouDing on this first; they joined the team working on this, and want to collaborate with you. (See their comment above). I recommend the three of you coordinate and see the design draft is something you all want to propose.

Hi Amy, 

Hope this finds you well. I'm volunteering at Wordplay this quarter and am not yet familiar with the new rules regarding project assignments, I am sorry about that. Also, I recognized that there might have been some misunderstanding; Olivia and Junna might not have known that I almost completed this design during the previous quarter. After our discussion, I feel it would be best for me to finalize it independently to maintain consistency and integrity of the work. Could you please review the current design and let me know if there are any adjustments needed? After incorporating your feedback, I will hand over this to Olivia and Junna.

**Comment by amyjko** [comment]
@JunnaC @oliviawei1102 Did you request to join this issue because you wanted to work with @YizhouDing? It sounds like @YizhouDing wants to work alone.

@YizhouDing, we'll move forward once we know @oliviawei1102 and @JunnaC's intent. They're interested in this, and so we don't want to exclude them without talking to them first. (Working alone on this is fine, but there are many benefits to multiple perspectives on a design).

**Comment by JunnaC** [comment]
> @JunnaC @oliviawei1102 Did you request to join this issue because you wanted to work with @YizhouDing? It sounds like @YizhouDing wants to work alone.
> 
> @YizhouDing, we'll move forward once we know @oliviawei1102 and @JunnaC's intent. They're interested in this, and so we don't want to exclude them without talking to them first. (Working alone on this is fine, but there are many benefits to multiple perspectives on a design).

Hi Amy, @oliviawei1102 and I can peer review @YizhouDing's proposal to add more ideas about the home page design, or we can change to another issue since Yizhou is almost done with the design.

**Comment by amyjko** [comment]
@YizhouDing, how do you feel about @oliviawei1102 and @JunnaC's proposal to peer review and help converge toward an approved design?

**Comment by YizhouDing** [comment]
Sure, that would be great!! Thank you for your help.

On Apr 16, 2024, at 8:16 AM, Amy J. Ko ***@***.***> wrote:

﻿

@YizhouDing<https://github.com/YizhouDing>, how do you feel about @oliviawei1102<https://github.com/oliviawei1102> and @JunnaC<https://github.com/JunnaC>'s proposal to peer review and help converge toward an approved design?

**Comment by JunnaC** [comment]
Heyy @amyjko 

After discussion with @YizhouDing, we think it’s better to put our ideas in the comments. Both Olivia and I also like the design of the blocks! So, we don't have much feedback on that. We have some other ideas to add to Erica's design about the layout for About, Right, and Donate. We came up with 5 design ideas for the re-layout. All these 5 put “About” next to the big logo of Wordplay to make it more intuitive if someone wants to learn about "Why does this place exist?"

**Design Idea 1:** Since we moved the about, we aligned Right and Donate on the same line to avoid scrolling and keep the page balanced and simplicity.
<img width="646" alt="component redesign 1" src="https://github.com/wordplaydev/wordplay/assets/91641486/004f8c3b-74d8-43cf-aad6-bec9fac18d65">


**Design Idea 2:** We created the website footer section, including a Contact component with buttons for GitHub and Discord. 
<img width="646" alt="component redesign 2" src="https://github.com/wordplaydev/wordplay/assets/91641486/09118d65-b2de-427c-8a2d-53e88099166e">


**Design Idea 3:** different layout of footer components
<img width="646" alt="component redesign 3" src="https://github.com/wordplaydev/wordplay/assets/91641486/0cb54dd6-2b2e-4f2d-ad5b-df904aa88ea0">


**Design Ideas 4:** different layout of footer components
<img width="646" alt="component redesign 4" src="https://github.com/wordplaydev/wordplay/assets/91641486/cba91246-cf0a-4bb1-a125-32e7d58e916c">


**Design idea 5:** We removed the box at the top, and put it at the footer part. By adding buttons for GitHub and Discord
<img width="646" alt="component redesign 5" src="https://github.com/wordplaydev/wordplay/assets/91641486/324195c3-a10d-429b-aff2-2c0b91af2d98">

**Comment by amyjko** [comment]
You tagged me; are you looking for design feedback this point, or still reconciling your ideas together? Just let me know when you want design review and you can tag me or Isabel.

One note while you're brainstorming: remember that this page needs to be responsive for all screen sizes, from smartphone to desktop; account for that in any layouts you design.

**Comment by YizhouDing** [comment]
Hi @amyjko, 
Based on @JunnaC and @oliviawei1102 's feedback, I've made several updates to our homepage:

<img width="607" alt="Screen Shot 2024-05-15 at 3 57 19 PM" src="https://github.com/wordplaydev/wordplay/assets/108030139/8fbece7a-dc61-4d83-97a7-a5bcbe4cede4">

- I've moved the login feature below our introduction to Wordplay to ensure users log in before navigating our coding features.
- I really appreciated the footer suggestions. I've included several components they mentioned. I placed the "beta" notice and feedback entry together in the footer. Placing the beta notice at the top does make it prominent, but it also takes up valuable space and might distract from other important content on our homepage. Additionally, I've added links for "About," "Donate," and "Rights" next to them.

Please let me know if you have any feedback. Once you respond, I'll add this section to the design specification!

**Comment by amyjko** [comment]
Thanks for the update @YizhouDing! I like the overall direction.

* Why is the border on login yellow, but the others are grey? (We don't have this design convention anywhere else on the site, so I'm looking for rationale for why to deviate from the existing design).
* Does the footer float, or is it anchored on the bottom of the page? If the latter, then no one will see the beta warning, which is very bad. Everyone must see the beta warning: we need everyone to know that things may not work as intended.
* How do you propose to wrap content on small screens?
* I have many tweaks I would make to the copy (the text you've included), but we don't have to wordsmith those here. The general direction is fine.

**Comment by JunnaC** [comment]
Here is a redesign for the home page of the large screen, with the corresponding medium and small screen. 
After talking with Amy, I just learned that more panels will be launched in the short future. So the change I made is moving the Login above the panels. In this way, users could always find the Login easily no matter how many panels are developed in the future.

For the small screen, the gray boxes will have a wider width(as shown in the screenshot)
<img width="646" alt="home page small screen" src="https://github.com/wordplaydev/wordplay/assets/91641486/8ca77c22-5f71-4467-bce2-63d7cdf3b8e6">

For the medium screen
<img width="646" alt="home screen medium screen" src="https://github.com/wordplaydev/wordplay/assets/91641486/2c67146e-9d59-4e73-a568-65d60c45633b">

For the large screen, enlarge the box sizes
<img width="646" alt="home screen large screen" src="https://github.com/wordplaydev/wordplay/assets/91641486/96a310d2-9993-4f9c-a1de-b5e1f6b709f0">

**Comment by JunnaC** [comment]
I plan to continue collaborating and working on this issue

**Comment by amyjko** [comment]
@YizhouDing @oliviawei1102, will you also be continuing work on this? (We need to know who's on the team, so please communicate your plans).

**Comment by YizhouDing** [comment]
Hi Amy,

I will keep working on it until it done!

On May 30, 2024, at 12:21 PM, Amy J. Ko ***@***.***> wrote:

﻿

@YizhouDing<https://github.com/YizhouDing> @oliviawei1102<https://github.com/oliviawei1102>, will you also be continuing work on this? (We need to know who's on the team, so please communicate your plans).

**Comment by oliviawei1102** [comment]
I will work and collaborate on it too!

**Comment by YizhouDing** [comment]
@amyjko 
Hi Amy, I updated the design specification with the new ideas and design we did last quarter, please let me know if there is anything we need to change!

**Comment by amyjko** [comment]
Thank you @YizhouDing. Overall, it looks good, and I'm ready to approve for building. There are a few inconsistencies and ambiguities that would be nice to clarify though:

* In some sketches, the login page appears above the blocks, in other pages below. Which is the design?
* The design spec mentions a language icon. Which icon? There's no icon shown, just a screenshot of "en-US", which already appears in the current design of the platform. There is no standard language icon on the internet, though there are some commonly used ones. Which are you proposing?
* There is a suggestion to redirect to login for several pages, but not all pages require a login to view (e.g., learn, galleries). Why would we redirect to login for those pages?

**Comment by YizhouDing** [comment]
> Thank you @YizhouDing. Overall, it looks good, and I'm ready to approve for building. There are a few inconsistencies and ambiguities that would be nice to clarify though:
> 
> * In some sketches, the login page appears above the blocks, in other pages below. Which is the design?
> * The design spec mentions a language icon. Which icon? There's no icon shown, just a screenshot of "en-US", which already appears in the current design of the platform. There is no standard language icon on the internet, though there are some commonly used ones. Which are you proposing?
> * There is a suggestion to redirect to login for several pages, but not all pages require a login to view (e.g., learn, galleries). Why would we redirect to login for those pages?

Hi Amy,
I've updated the comments and addressed the issues you highlighted, including adding an explanation for the language icon.  Thank you for the feedback. For the login section, I've positioned it above the panels to increase its visibility, encouraging users to log in to secure their data and track their study progress. Please let me know if there is anything else that is unclear in the spec!

**Comment by amyjko** [comment]
Thanks for the clarifications! I've marked this buildable, meaning the design is close enough to build. Either someone will take it up, or I'll get to it eventually. Thank you for your design contributions!

**Comment by amyjko** [comment]
I just released an implementation of the redesign. Thank you everyone for contributing an excellent new design! If you see something that I missed, or think it needs further tweaks, feel free to reopen this issue.
