### ISSUE TITLE
Playwright e2e tests falsely pass untested scenarios.

### ISSUE THREAD

**Issue by meepsterleapster** [wordplaydev/wordplay#402]
## Expected behavior

Playwright tests should load a webpage, run assigned tests and give a pass or fail result depending on context from webpage.

## Actual behavior

When running playwright as a function, playwright does wait for a page to load in order to conduct its tests. Instead the test will always pass, even on tests built specifically to fail

1. In VScode Terminal
2. run the command: ``npx playwright test tests/home.spec.ts --ui``
3. When playwright UI pops up, click the run test button in the top left
4. tests in functions(EX: "learn link works") do not load page ,remain on blank screen, and passes test

## Screenshots
Example of functions with the issue. Adding await to the function does not fix the issue,  fake function in red will pass tests it should not 
<img width="535" alt="image" src="https://github.com/wordplaydev/wordplay/assets/155786514/4e611314-cf6d-4577-8ccc-17621d57766f">

Here is an example of the playwright UI, showing blank screen tests passing
<img width="936" alt="image" src="https://github.com/wordplaydev/wordplay/assets/155786514/5064db05-15f1-4fd2-9f7a-39784e369b1b">

A normal test should look like this:
<img width="940" alt="image" src="https://github.com/wordplaydev/wordplay/assets/155786514/1f1703a2-c704-4b48-8b04-6e25a0df5d1d">

## Environment

Desktop

OS + version: [Windows 22H2]
Browser + version [Chrome Version 121.0.6167.185 (Official Build) (64-bit)]

Operating Environment
VScode
Playwright

**Comment by amyjko** [comment]
Removing `debugger` label, that's for the Wordplay debugger functionality, not for tests. I'll create a label for tests.

**Comment by amyjko** [comment]
@meepsterleapster I just resolved this; there were a few lurking issues, including 1) not waiting for the test to complete, 2) multiple matching links, causing a strict mode ambiguity failure. The test should be more robust now.
