### ISSUE TITLE
Images are not sized correctly in the Chinese version

### ISSUE THREAD

**Issue by michelleldang** [wordplaydev/wordplay#410]
## Expected behavior

The images on the gallery page should fit within the image box.

## Actual behavior

Some rotating images in the gallery page are cut off/ not sized to fit.
1. Go to the gallery page (https://wordplay.dev/galleries)
2. Switch to Chinese

## Screenshots

![image](https://github.com/wordplaydev/wordplay/assets/91906403/0c9645dc-5eeb-4448-9106-b067b8de54f0)

## Environment

Desktop, Windows 11
Chrome 122.0.6261.95

**Comment by amyjko** [comment]
@michelleldang Can you add exact browser and version numbers, as well as exact operating system and version numbers? These can affect font measurements. (That's why we ask for them).

The reproduction steps also need to be more precise. Which gallery page are you talking about? Provide an exact URL.

**Comment by amyjko** [comment]
@michelleldang We're still waiting for a reply from you on this. Can you please add complete version information, so we can reproduce?

**Comment by michelleldang** [comment]
@amyjko Is this the information you need? 
Edition	Windows 11 Home
Version	23H2
Installed on	‎1/‎27/‎2023
OS build	22631.3296
Experience	Windows Feature Experience Pack 1000.22687.1000.0

**Comment by amyjko** [comment]
Yes. Please put that in the issue body, not a comment, so others can find it. (It's a required part of the issue template that shouldn't be skipped).

**Comment by amyjko** [comment]
I believe this issue is referring the project previews on the gallery page. I examined different locales, and it's also not particular to the Chinese locale. Some emoji are centered, some are not; it seems to be a property of the font and how we're treating its baseline.
