### ISSUE TITLE
Chinese Localization Inconsistencies

### ISSUE THREAD

**Issue by ahuynh00** [wordplaydev/wordplay#411]
## Bolding inconsistency in Beta

Inside the English version of the Beta popup (bottom bar), the first sentence bolds "beta", but it isn't bolded in the Chinese Beta popup.
<img width="1324" alt="English vs Chinese Beta Popup" src="https://github.com/wordplaydev/wordplay/assets/91906524/22485b2f-5f84-49e5-b975-b564198c6d6b">

## Settings Space Indicator
The setting space indicator is "$! 空格指示器" when the locale is changed to Chinese, and the bottom bar settings gear is clicked. The very last setting option is the setting space indicator.

## Inconsistent Icons in the setting options for layout
In the English version of layout (bottom bar settings gear), all arrow icons are filled with a black square background in both Safari and Chrome. In the Chinese version on Safari (Version 17.0 (19616.1.27.211.1)), the vertical arrow doesn't have the filled square background. On Chrome (Version 122.0.6261.111), neither of the arrows have the filled black square background.

English:
<img width="463" alt="Setting Icons in English Locale" src="https://github.com/wordplaydev/wordplay/assets/91906524/c9d19fe0-de40-4827-8421-88e8e58f77b2">

Safari Chinese:
<img width="375" alt="Chinese Locale Setting Icons in Safari" src="https://github.com/wordplaydev/wordplay/assets/91906524/63abd5ae-1c8e-4bc3-a372-c6fe51b29e2f">

Chrome Chinese:
<img width="343" alt="Chinese Locale Setting Icons in Chrome" src="https://github.com/wordplaydev/wordplay/assets/91906524/18b1747a-e692-48d6-9821-10ae552148fb">

## Palette 
Go to learn, and on the secondary bottom action bar, select palette.

The Chinese locale is missing translations for **format** and **aura** in the palette options, they show up in English. Instances of this are found in the following sections under Learn:
- The Verse: Program, Unparseable
- Its The Little Things: Values, Text, Prefix, Nothing
- Cast Party: Convert, Decisions
- Scene Change: Time, Key, Pointer, Button, Volume, Random, Placement, Chat, Reaction
- Take the Stage: Phrase, Sequence, Scene, Choice
- Callbacks: Memories, Bind, Block, Functions, Structures, Explain

Other instances of English found in the Chinese locale of palette include:
- **Clockwise** and **Counter** in Ensembles: Lists, Sets, and Mappings
- **Color** in Scene Change: Motion, and Take the Stage: Output
- **Straight** in Denouement: Codependency

The number of options in the palette also varies between English and Chinese throughout the sections of Learn. In The Verse: Program, the English palette contains 25 options while the Chinese palette contains 20.

## The **Start** button inconsistent translation
Start button is located on the secondary bottom bar of Learn page.
It seems like if you have more than one language listed at the bottom right corner (next to the keyboard in the Learn window), **Start**  will be written in the very first language on that list, even if the current locale you are on is in a different language.

Below are examples of **Start** button being in a language other than the primary chosen locale:
<img width="1511" alt="Yes And No" src="https://github.com/wordplaydev/wordplay/assets/91906524/9f4a8e75-7bf0-4a79-9951-f4a09fddde66">
<img width="1497" alt="Yes And No" src="https://github.com/wordplaydev/wordplay/assets/91906524/6ba626fd-f5c5-496e-bb37-a953c6e9ac6b">
<img width="1512" alt="Scene 1" src="https://github.com/wordplaydev/wordplay/assets/91906524/7eb941a2-b5a2-4988-8f9b-1985b29626be">
<img width="1512" alt="Pasted Graphic 4" src="https://github.com/wordplaydev/wordplay/assets/91906524/3c1dc4c0-0721-49e0-8301-2dcdb985757e">

In Its the Little Things: Truth, the palette options also contain Chinese in both the English and Spanish locales as shown in the images above

## Environment

Desktop

-   mac OS 14.0
-   Safari 17.0
-  Chrome 122.0.6261.111

**Comment by amyjko** [comment]
Thanks @ahuynh00! These are all great. Feedback on this report:

* There are many distinct issues in this report, each requiring a different resolution. Each one should be a separate issue. You have five headers; each one should be a separate report. Please create those and close this one, so they can be worked on independently.
* If you haven't already, please consult with the Chinese locale team, to ensure that these aren't already being worked on in an existing branch or a different issue.
