### ISSUE TITLE
Chinese Locale Bolding ("Beta")

### ISSUE THREAD

**Issue by ahuynh00** [wordplaydev/wordplay#415]
## Bolding inconsistency in Beta

Inside the English version of the Beta popup (bottom bar), the first sentence bolds "beta", but it isn't bolded in the Chinese Beta popup.
<img width="1324" alt="English vs Chinese Beta Popup" src="https://github.com/wordplaydev/wordplay/assets/91906524/22485b2f-5f84-49e5-b975-b564198c6d6b">

## Environment

Desktop

-   mac OS 14.0
-   Safari 17.0
-  Chrome 122.0.6261.111

**Comment by Davidxuwuhu** [comment]
i can work on this!

**Comment by amyjko** [comment]
Assigned! This should be an easy one.

**Comment by Davidxuwuhu** [comment]
Hi I got a problem pushing the work to my branch, it says permission to wordplaydev/wordplay.git denied. I am using the correct uw credentials but it somehow still doesn't work. Is there any way to solve this? Thank you

**Comment by amyjko** [comment]
Have you read the dev wiki? All of the instructions for how to submit a pull request from a fork are there. Read the wiki thoroughly and let us know if you have questions.
