### ISSUE TITLE
Chinese Locale: Settings Space Indicator Text

### ISSUE THREAD

**Issue by ahuynh00** [wordplaydev/wordplay#416]
## Settings Space Indicator
The setting space indicator is "$! 空格指示器" when the locale is changed to Chinese, and the bottom bar settings gear is clicked. The "setting space indicator" is the very last setting option.

## Environment

Desktop

-   mac OS 14.0
-   Safari 17.0
-  Chrome 122.0.6261.111

**Comment by twu29** [comment]
hi @amyjko I'm interested in working on this issue. Could you assign it to me and provide me with some guidance please?

**Comment by amyjko** [comment]
@twu29 assigned. It looks like this is just a missing translation in the Chinese locale. See `Settings.svelte` for where the UI is implemented and which locale string is being rendered.

**Comment by twu29** [comment]
@amyjko Hi Amy, I double-checked this issue on both Chrome and Safari on my computer (mac). It seems that when switching to the Chinese version, it now only displays "空格指示器" instead of "$! 空格指示器." Based on this, I believe this is no longer an issue.

**Comment by amyjko** [comment]
Looks like this is resolved then. I'll close.
