### ISSUE TITLE
Background color fills other parts of the screen when fullscreening editor tab

### ISSUE THREAD

**Issue by brendaaank** [wordplaydev/wordplay#444]
## Expected behavior

When pressing the full screen button on the code text editor, the rest of the UI panels should keep their colors, and the stage should minimize.

## Actual behavior

In the tutorial, pressing the full screen button for the code editor, the Learn tab takes the orange color of the stage as the stage disappears.

1. Go to [https://wordplay.dev/learn?locale=en-US&act=1&scene=4&pause=7&concept=unparsable](url)
2. Click on the full screen button on the top edge of the code editor (next to "start")

## Screenshots

The button in question
![image](https://github.com/wordplaydev/wordplay/assets/78980484/f7a3b809-2e65-4d9d-9e53-a27f7b5409ec)

The error
![image](https://github.com/wordplaydev/wordplay/assets/78980484/87011eac-2b2a-44e8-9937-b143f321b87a)

## Environment

Desktop

-   Windows 11
-   Chrome 123.0.6312.122

**Comment by amyjko** [comment]
Resolved by f2e436d.
