### ISSUE TITLE
Adding Traditional Chinese to Wordplay

### ISSUE THREAD

**Issue by shockwave656** [wordplaydev/wordplay#449]
**What's the problem?**
I will be trying to add traditional Chinese to Wordplay, to give users of traditional Chinese characters the option to use Wordplay in their native language. 
**What's the design idea?**
I will start by translating the version of Wordplay in simplified Chinese to traditional Chinese.

**Comment by amyjko** [comment]
Thanks @shockwave656! Remember to use the issue templates when creating issues; they contain important information that you need to include. This issue should be an enhancement, and in particular should detail anything that needs to be added beyond just a translation (e.g., layout changes, additional support in the programming language, etc). Please review the enhancement template and format the issue accordingly.

**Comment by shockwave656** [comment]
Closed: I have completed a basic traditional Chinese homepage for wordplay based off the provided template. I will submit a pull request for this. There can be edits made later on, especially if people suggest better translation, but the basic work of setting up the home page is completed.

**Comment by shockwave656** [comment]
Also there still needs to be work done on the tutorial, but I think that can be done on a separate issue page.
