### ISSUE TITLE
Drag and Drop Code Snippets from Tutorial not Working

### ISSUE THREAD

**Issue by elianna-b** [wordplaydev/wordplay#466]
#### Expected Behavior
In the tutorial, when prompted to type code, there is an option to drag and drop code snippets into the IDE. The code is highlighted in blue with `' '` surrounding the prompt. The user can hover over it, and it is highlighted with the cursor changing to the drag icon. The user should then be able to click, hold, drag the snippet into the IDE, and have it pasted there.

#### Actual Behavior
1. Go to [Tutorial: Program 6/11](https://wordplay.dev/learn?locale=en-US&act=1&scene=2&pause=6&concept=program).
2. Hover over the blue `'hello'` code in the tutorial text.
3. The text is highlighted and the cursor changes to the grab icon.
4. Error: Attempting to hold and drag the snippet does not work. The snippet cannot be dragged or dropped into the IDE, resulting in a loop of clicking without functionality.

#### Screenshots

**Tutorial Page Overview:**
![Tutorial Page Overview](https://github.com/wordplaydev/wordplay/assets/121900086/d8998faa-8a3c-4c6a-9485-0ed565ae0a6b)

**Hover Feedback:**
![Hover Feedback](https://github.com/wordplaydev/wordplay/assets/121900086/4a020245-feac-403e-9e2a-db1bfa272670)

**Click Feedback:**
![Click Feedback](https://github.com/wordplaydev/wordplay/assets/121900086/4db5baf7-8215-4ed3-b02d-5db49ed015bf)

There is no dragging and dropping functionality displayed, although this feature is intended to exist.

#### Environment
- **Laptop:** Windows 11, version 23H2
- **Browser:** Chrome Version 124.0.6367.203 (Official Build) (64-bit)

#### Design Specification
No new design needed, this is a bug fix.

**Comment by amyjko** [comment]
Thanks for reporting! I'm grabbing this one, it'll be an easy fix.
