### ISSUE TITLE
Adding Back Buttons in Galleries 

### ISSUE THREAD

**Issue by lasyasr** [wordplaydev/wordplay#472]
## What's the problem?

-  When going through the projects there are no back buttons that allow the user to return to the page they were on. We would need to add back buttons on pages that take them away from the "main page" which would be Gallery in our case. When they are going to the galleries page and clicking on a specific project if the user wants to go back to the page to find other options, they would have to navigate to the bottom of the page and restart the user journey. The students and users of the website would be the group of people. In the current design, no indications allow the user to backtrack, except for the default website arrow. 

## What's the design idea?

Hello @amyjko @joonpiter  here is a design idea for this issue!
We should add an in-app back arrow to allow the user to backtrack and resume their journey. 
In this design, we would implement the same icon as a back arrow to promote consistency. Users between the ages of 12-18 would understand that it would mean they could click on the website and have the freedom and ability to exit if they wished. The color of the arrow is consistent with the header so that the user is aware. 

![image](https://github.com/wordplaydev/wordplay/assets/114948259/6590562b-c739-4074-a243-3b793934be8d)
![image](https://github.com/wordplaydev/wordplay/assets/114948259/a9f74a0b-a41f-4190-bb3f-3f8ae848297a)

## Design specification
Hi @amyjko! I noticed that when people use the system back button, the page usually refreshes and leads them back to the top of the previous page. This way the user loses track of their journey on the page. (If we add a custom back button, we could return to the state of the page they were on before clicking on the element). Another reason is that Games is a subpage from Galleries for example, if we added a custom button at the top the user would remember that there are more projects they could view from the Gallery Page. 
As for the back button for the games and projects, it would remind the user that if they do not wish to continue playing/experimenting with the project they always have the option of returning to the list of other projects. Though the back button exists, for younger users seeing the option to back out of the game gives a sense of control on the website (not just from the browser button). To make it clear to the user that they can exit the game and try other projects, In this update design proposal I added "Exit" so that user is aware. 
![image](https://github.com/wordplaydev/wordplay/assets/114948259/4e2b49fa-30fb-45c2-8a87-5493a18f4ca0)
![image](https://github.com/wordplaydev/wordplay/assets/114948259/6590562b-c739-4074-a243-3b793934be8d)
_Reporters can leave this blank. Designers should write a detailed, precise description of what is to be built. If images are necessary to convey this precisely, make sure to include image descriptions, so everyone can see what is in the image. Do not link to external documents; everything should be embedded here. Once the design is approved, we will remove the `needs design` tag and replace it with the `buildable` tag, signalling that it can be built._

**Comment by amyjko** [comment]
Interesting idea! There are lots of reasons there isn't a back button on the galleries page or a project page:

* The back button in the browser already has this functionality
* On project pages, it's not clear what it would mean; someone could work for 30 minutes on a project and then forget what they'd be returning back to.

Do you have a sense of what you'd want the back button to mean and why? Alternatives include:

* The previously visited URL (identical to the browser back button)
* The list of galleries
* The list of projects

**Comment by joonpiter** [comment]
@lasyasr Amy left comments on aspects to continue iterating on

**Comment by amyjko** [comment]
@lasyasr, can you please clarify whether you're continuing work on this? Your post was supposed to indicate whether you are continuing work.

**Comment by lasyasr** [comment]
Hi, I will not continue to work on this, I will un-assign myself from this issue.

**Comment by amyjko** [comment]
Closing this issue. While there is a clear need to be able to navigate back, it is redundant with the browser's back button, and creating a redundant back button in the application that is redundant with the browser back button may only add confusion.
