### ISSUE TITLE
Truth 9/15 has a logical error typo where & should be |

### ISSUE THREAD

**Issue by DavidCooperWCU** [wordplaydev/wordplay#480]
## Expected behavior

Their paragraph from false should be

```
Not wrong.  false or false equals false, but true 
otherwise.
```

## Actual behavior

<img width="418" alt="Truth9:15" src="https://github.com/wordplaydev/wordplay/assets/22147366/c9a94253-d379-4853-91c0-2556771ec85e">

The above is from Truth 9/15 of the Learn tutorial

**Comment by amyjko** [comment]
Thanks for reporting!
