### ISSUE TITLE
Account for name conflicts during project translation

### ISSUE THREAD

**Issue by amyjko** [wordplaydev/wordplay#486]
## Expected behavior

Our project translation feature should account for duplicate names when creating translations. For example, if a program like this were translated from Spanish to English, it should not create a conflict:

```
hola/es: 'hola'
hello/en: 'hi'
hola + hello
```

## Actual behavior

Translating the above from Spanish to English creates a new name for `hello` named `hola`, which creates a duplicate name conflict.

## Design specification

Detect when a conflict will occur with a new name, and instead of giving it the same name, append a number to `2` to the end of the name, to prevent the conflict.

**Comment by twu29** [comment]
@amyjko I'm interested in working on this issue. Could you assign it to me please?

**Comment by ahsoj22** [comment]
@amyjko I am also interested in working on this issue, I would like to be assigned to it.

**Comment by ahsoj22** [comment]
@amyjko I'm interested in working on this issue, I would also like some guidance on where to get started

**Comment by amyjko** [comment]
@ahsoj22 and @twu29 agreed to collaborate on this in person.

See `translate.ts`, which is the function that creates a translated `Project` using Google Translate. That's the function that needs to account for name conflicts. Currently, it just adds names in the new language independent of whether they are already defined. (e.g., if a program had the name `gato` and another name cat was translated into Spanish, then there would be two `gato`s, creating a name conflict.
