### ISSUE TITLE
Unclear when animations are disabled, leading to confusion about scene playback

### ISSUE THREAD

**Issue by thesmolcoder** [wordplaydev/wordplay#488]
## Expected behavior

When an animated scene is created, the stage should show the scene that was created in the phrase order.

## Actual behavior

The stage is partially showing a part of the first phrase and then jumping to the last phrase skipping the phrases in between. 

1. Click on a project with an animated scene and open the stage
2. Let it run
3. See error

## Screenshots
<img width="1540" alt="Screenshot 2024-06-17 at 5 00 33 PM" src="https://github.com/wordplaydev/wordplay/assets/47015663/433ea7ea-244d-4df2-89c5-41a1951606dc">
<img width="1541" alt="Screenshot 2024-06-17 at 4 58 08 PM" src="https://github.com/wordplaydev/wordplay/assets/47015663/2dd7db89-68b1-4bf5-9772-ae00139cebfc">

## Environment

Desktop

-   OS + version: Mac OS 14.5
-   Browser + version: Chrome Version 126.0.6478.62

## Cause

The cause of this turned out to be that animations were disabled in @thesmolcoder's settings. This is confusing; we probably need some indicator that animations are disabled on stage.

## Remedy

Add an indicator on stage that makes it clear that animations are disabled. The indicator should use the same icon as the setting, but also be highlighted in some way, and only visible during edit mode.

**Comment by amyjko** [comment]
@thesmolcoder Can you give a link to the project? I'll need that to be able to reproduce and investigate the issue.

**Comment by thesmolcoder** [comment]
@amyjko I just found what the issue was. My Wordplay animation settings were at stop. Everything is working correctly now.

**Comment by amyjko** [comment]
Oh! That's a good catch. But I'm going to reopen and rename this issue, because that seems like a major usability problem. There should be a stronger indicator that animations are turned off.
