### ISSUE TITLE
Typo in Learn Module - Text

### ISSUE THREAD

**Issue by thesmolcoder** [wordplaydev/wordplay#495]
## Expected behavior

Should say double " "

## Actual behavior

Currently says double ' '

1. Go to 'Learn'
2. Click on the drop-down and navigate to 'Text' under 'It's the little things'
3.  Click the arrow until you get to the 4th slide
4. Read through on the slide

## Screenshots

<img width="1727" alt="Screenshot 2024-06-25 at 11 47 19 AM" src="https://github.com/wordplaydev/wordplay/assets/47015663/cc4e71bf-2bd7-4313-9ee5-54983c937097">

## Environment

Desktop

-   OS + version: Mac OS 14.5
-   Browser + version: Brave Version 1.67.119 Chromium: 126.0.6478.114 (Official Build) (arm64)

**Comment by amyjko** [comment]
Thanks for reporting!
