### ISSUE TITLE
After pressing the 'en' button, emoji's are shown instead of words

### ISSUE THREAD

**Issue by thesmolcoder** [wordplaydev/wordplay#498]
## Expected behavior

When clicking the 'en' button, Wordplay should be set to show words.

## Actual behavior

When clicking the 'en' button, it shows the emojis instead.

1. Go to the top
2. Select 'en'
3. Program something in Wordplay 
4. Notice emojis show instead

## Screenshots

<img width="347" alt="Screenshot 2024-06-26 at 1 13 06 PM" src="https://github.com/wordplaydev/wordplay/assets/47015663/ce956307-7453-4752-aaf1-79c774bb3253">
<img width="362" alt="Screenshot 2024-06-26 at 1 12 44 PM" src="https://github.com/wordplaydev/wordplay/assets/47015663/2e93a5cf-9c09-4717-9c58-78132610b56b">

## Environment

OS + version: Mac OS 14.5
Browser + version: Brave Version 1.67.119 Chromium: 126.0.6478.114 (Official Build) (arm64)

**Comment by amyjko** [comment]
Resolved by 9d2fedf45c0d27d71fbb02eaffcd669146ed7b2c.
