### ISSUE TITLE
Commenting out causes the cursor to not go near the first star

### ISSUE THREAD

**Issue by thesmolcoder** [wordplaydev/wordplay#504]
## Expected behavior

When commenting something out, the cursor should be able to go by the first * 

## Actual behavior

1. Click the ** button to comment out some code
2. Try to move the cursor to the beginning of the commented-out section of the code
3. Notice that the cursor will not go by the first * 
4. When you click the right arrow once and then delete at the position it will not move from, it deletes the first star.

## Screenshots
<img width="588" alt="Screenshot 2024-06-28 at 4 38 31 PM" src="https://github.com/wordplaydev/wordplay/assets/47015663/7a01def3-c25f-4156-a784-c7dbc3f91726">

## Environment

Desktop

- OS + version: Mac OS 14.5
- Browser + version: Brave Version 1.67.119 Chromium: 126.0.6478.114 (Official Build) (arm64)

**Comment by amyjko** [comment]
Thanks Rayana! I'll investigate.

**Comment by amyjko** [comment]
It looks like this issue was related to emojis, which are both more than one character when encoded, and non-fixed width. I rewrote the space measurement algorithm to account for both, so it should be much more robust to non-whitespace characters in comments now.
