### ISSUE TITLE
Typo on Phrase Module - Explanation of Hue

### ISSUE THREAD

**Issue by thesmolcoder** [wordplaydev/wordplay#505]
## Expected behavior

It should say hue instead of chroma during Phrase's explanation of the hue. 

## Actual behavior

1. Navigate to the 'Take the stage module'
2. Click on 'Phrase'
3. Navigate to the 26th slide for Phrase

## Screenshots
<img width="512" alt="Screenshot 2024-06-28 at 4 56 27 PM" src="https://github.com/wordplaydev/wordplay/assets/47015663/a05e0c25-3672-4dbc-9213-56740d62e1cc">

## Environment

Desktop

- OS + version: Mac OS 14.5
- Browser + version: Brave Version 1.67.119 Chromium: 126.0.6478.114 (Official Build) (arm64)

**Comment by amyjko** [comment]
Thank you for reporting!
