### ISSUE TITLE
Dragging from Guide results in emotes to show instead of words

### ISSUE THREAD

**Issue by thesmolcoder** [wordplaydev/wordplay#506]
## Expected behavior

When in the all-text mode, if you drag from the guide, it stays in the localized mode which is the emoji. It is expected that dragging from the guide while in the all-text mode would result in the item being dragged to be in all-text

## Actual behavior

1. Be in all-text mode by clicking on the world symbol
2. Go to 'Guide' 
3. Drag a function onto the editor
4. Notice the dragged function is in localized mode

## Screenshots

<img width="1452" alt="Screenshot 2024-07-01 at 3 46 09 PM" src="https://github.com/wordplaydev/wordplay/assets/47015663/dc49342c-49fa-497d-9bda-f3e20a4344c3">

## Environment

Desktop

OS + version: Mac OS 14.5
Browser + version: Brave Version 1.67.119 Chromium: 126.0.6478.114 (Official Build) (arm64)

**Comment by amyjko** [comment]
Ah, interesting case. I can see why that would be a reasonable expectation. At the moment, it's just copying exactly what is in the guide verbatim, without modifying any of the references.

I think one issue here is communicating expectations about what that switch does. Currently, the two behaviors are 1) show all localized text, no matter how many different translations are included, or 2) only show text in the currently selected locales. So it has nothing to do with emoji/non-emoji names.

So there are a few ways forward on this issue:

* Have a third mode, which might be something like "prefer symbol names"
* Clarify the behavior of those two modes (e.g., change their icons to convey that it's all the names, or only the selected locale names)

What do you think would be the more useful behavior?

**Comment by thesmolcoder** [comment]
I think the third mode may be better to allow for an alternative option but I feel better clarification also may be needed. I got a bit confused about what each was doing and this may have been due to seeing the 'en' so I automatically thought it was supposed to be in the language that I had it set to and was not expecting to see any symbols. Whereas when I saw the world symbol, I was expecting to see the symbols (Thinking of it as world languages and the symbols would be something most would understand without having to communicate in solely one language). Some may prefer to only see words/characters in their language and no symbols at all.

**Comment by amyjko** [comment]
I've thought about this design and think a way to proceed is as follows:

* Change the behavior of this toggle to only hide and show names that are outside the selected locale. It should not ever show symbolic versions of names, unless those are explicitly in the code. The offending function that is doing this is `Token.localized`, which is preferring the symbolic name over names in the program text.
* Add a third mode which prefers symbolic names, for those who might like the emoji names.
* When copying code from the palette, copy the word name, and not the symbolic name in references.
