### ISSUE TITLE
Reevalting a Webpage stream with a new URL returns previous stream result

### ISSUE THREAD

**Issue by azmec** [wordplaydev/wordplay#507]
## Expected behavior

When reevaluating a program containing a `Webpage` stream with a new `url` argument, the stream should evaluate to the content at that new URL or a number indicating the percentage of the page that is loaded.

## Actual behavior

Instead, the stream evaluates to the previous stream result.

1. Copy and paste the following code into a Wordplay project.
    ```
    chat: Chat()
    url: "https://www.google.com" … ∆ chat … chat
    webpage: Webpage(url)

    Stage([Phrase(webpage → '')] place: Place(0m 0m -15m))
    ```
2. Enter a complete HTTPS URL into the message box and hit `Enter`.
3. Step back one input in the program timeline.
4. Step forward 20 steps in the timeline. Observe that `Webpage` has been passed a new argument.
5. Step forward 2 steps. Observe that `Webpage` is evaluating to the previous value despite the new argument.

## Screenshots
Below is an image of the Wordplay IDE at Step 4.

![Image of Wordplay IDE at Step 4](https://github.com/wordplaydev/wordplay/assets/65310073/70860ac6-d7e0-4afd-95fe-6161fb6e5bd1)

Below is an image of the Wordplay IDE at Step 5.

![Image of Wordplay IDE at step 5](https://github.com/wordplaydev/wordplay/assets/65310073/8af3ff49-023a-4f26-8e86-ba5864cad0d3)

## Environment

Desktop

-   OS + version: Void Linux x86_64 6.6.35_1
-   Browser + version: Firefox 127.0.2_1

**Comment by amyjko** [comment]
Excellent issue, thank you for the reproduction steps!
