### ISSUE TITLE
Text cursor sits between lines of code following a language tag

### ISSUE THREAD

**Issue by azmec** [wordplaydev/wordplay#514]
### What happened?

The text cursor should be aligned with the line of code the user is currently typing in. However, when the text cursor is on a line following an explanation with a language tag, the cursor sits in-between lines.

1. Copy and paste the below code into a Wordplay project.
```
``Welcome to your blank project!``/en

Phrase("foo bar")
```
2. Move the text cursor to the second, empty line of code.
3. Observe that the text cursor sits between the second and third lines of code.
4. Type any character. Observe that the cursor jumps to the second line of code as it normally should.
5. Empty the second line.
6. Remove the language tag on the first line of code.
7. Move the text cursor to the second line of code. Observe that it is aligned with the second line of code.

### Anything else?

The below image shows text cursor sitting between the second and third line, as it should in step 3.

![Screenshot of the text cursor sitting between the second and third line of a  Wordplay performance. The text cursor is at the start of the second and third lines.](https://github.com/wordplaydev/wordplay/assets/65310073/cede05c6-4bfb-41eb-acbf-cd3e3b3823bc)

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

Linux

**Comment by amyjko** [comment]
Reproduced on Chrome, Safari, Edge, and Arc. Thanks for reporting!

**Comment by amyjko** [comment]
Diagnosed:

* `CaretView.computeLocation()` relies on view of prior token to compute position with `caret.source.getNextToken(token, -1)`
* When prior token is a hidden language tag, its bounding client rect is not accurate, so we get an invite position for the caret.

Fix:
* Find the prior token that does not have the `hide` class on it.
