### ISSUE TITLE
Delete button for archived projects does not appear

### ISSUE THREAD

**Issue by azmec** [wordplaydev/wordplay#515]
### What happened?

On [`wordplay.dev/projects`](https://wordplay.dev/projects), archived projects should have a "⨉" button to the right of the "↑🗑️" button. However, the "⨉" button does not appear after archiving a project. It appears only if the page is viewed from another browser while logged into the same account _or_ after the browser's cache for Wordplay is cleared.

1. Go to the Projects page.
2. Create a new project using the "Animated Sequence" template.
3. Return to the Projects page.
4. Archive the project you just created.
5. Scroll down to the "Archived" section. Observe that the "↑🗑️" button is present but the "⨉" button is not.

To see the "⨉" button, you can either

1. Open the Projects page in another browser and log into your account. If you used Firefox before, use Chrome here.
2. Observe that the "⨉" button is present for the archived project.

Or

1. Clear the cache for Wordplay on the browser you originally used.
2. Open the Projects page and log into your account.
3. Observe that the "⨉" button is present for the archived project.

### Anything else?

Below is a screenshot of the defect in Chromium and Firefox. The top window is a Chromium instance, the bottom window is a Firefox instance. The "⨉" button does not appear consistently across archived projects or browsers.

![image](https://github.com/wordplaydev/wordplay/assets/65310073/7f69026c-61f1-458f-9bbc-857ccd29a745)

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

Linux

**Comment by amyjko** [comment]
Thanks, will investigate.
