### ISSUE TITLE
Stage does not display translated text

### ISSUE THREAD

**Issue by azmec** [wordplaydev/wordplay#517]
### What happened?

Text with translations should render onto the stage in the language prescribed by the user's selected locale. Instead, the first available translation is rendered onto the stage.

1. Open a blank Wordplay project.
2. Change locale to Espanol, Mexico.
3. Copy and paste `characters: 'Wordplay outputs typography.'/en'Wordplay genera typografia'/es` into the project.
4. Observe that the stage displays the English translation, "Wordplay outputs typography".
5. Append the line `Phrase(characters)` to the project.
6. Observe that the stage displays the English translation.

### Anything else?

Below is a screenshot of the bug for literal text.

![image](https://github.com/wordplaydev/wordplay/assets/65310073/a2517977-469c-489d-914f-d11095387f8f)

Below is a screenshot of the bug for translated text passed to a `Phrase`.

![image](https://github.com/wordplaydev/wordplay/assets/65310073/9149f1ce-1c41-43ef-b9ce-53f7596e23f2)

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

Linux

**Comment by amyjko** [comment]
Resolved by a8f6e303bf2586f7e68d8cc12eab450ca2ff0dcd.
