### ISSUE TITLE
Container visual selection encompasses line numbers

### ISSUE THREAD

**Issue by azmec** [wordplaydev/wordplay#518]
### What happened?

Line numbers to the left of the program source should not appear to be selected by visual selectors. Instead, they are.

1. Copy and paste the below code into a Wordplay project.
```
phrase1: Phrase("This is Phrase #1")
phrase2: Phrase("This is Phrase #2")

Group(Stack() [phrase1 phrase2])
```
2. Move the text cursor to the end of Line 4.
3. Click the "Select container button" twice.
4. Observer that the "1" for Line 1 is contained in the visual selection.

### Anything else?

Below is an image displaying the defect.

![image](https://github.com/wordplaydev/wordplay/assets/65310073/c943133e-f371-4149-a576-17d3bf3ea137)

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Linux

**Comment by amyjko** [comment]
Resolved by 5904dce8cd490a2ca717d44264d931077ab5030f.
