### ISSUE TITLE
Teacher account management

### ISSUE THREAD

**Issue by amyjko** [wordplaydev/wordplay#519]
### What are you trying to do that you can't?

Students regularly forget passwords. Enable teachers to be the keeper of the usernames and passwords.

### What is the idea?

* Allow teachers to create accounts in bulk
* Set user names with a standard format
* Have a way for teachers to see passwords or reset them so students can get them
* Retain a mapping between usernames and student provided information so that teachers know who they are
* See student metadata on the site rather than usernames

### Design

The proposed UX is as follows:

- [x] Teachers request a teacher account, which gives them them the ability to make a class full of student accounts, create galleries associated with a class that automatically include all of the students in the class
- [x] Teachers visit a "teach" page to create a class. The page explains the purpose: organize classes of students.
- [x] To create a class:
  - [x] Teachers provide a name and description for the class and newline separated list of comma separated student information. 
  - [x] Names can be any number of comma separated fields, including given names, family names, student numbers.
  - [x] Globally unique usernames are generated from the provided information that uses as many characters of the two names given as possible. 
  - [x] Passwords are randomly generated sequences of Latin characters and numbers. 
  - [x] In the class, a mapping between each account generated and the original metadata is preserved so that teachers can refer to it later, and update it.
  - [x] Upon submission of the information, a download begins that includes the username, password, and metadata for each student. These cannot be retrieved, and so they are automatically downloaded.
- [x] From the class page, teachers can create a gallery associated with the class, which includes everyone in the class as creators and the teacher as a curator.
- [x] Teachers can bulk add and remove students from the class, providing the same information as when first creating the class. 
- [x] Teachers can add or remove classes to existing galleries.
- [x] Removing a student from a class removes them as creators from the galleries associated with the class

### Implementation

- [x] Create a `Learner` schema:

```
type Learner = {
  metadata: string[]; // A list of identifiers whose meaning is known only to the teacher
  username: string; // The account name given to the learner
  id: string; // The account ID generated
}
```

- [x] Create a `Group` schema (avoiding the reserved `class` keyword):

```
type Group = {
  id: string;
  name: string;
  description: string; // Any information the teacher wants to associate with the class.
  teachers: string; // The teacher uids that oversee the class
  learners: Learner[];
  galleries: string[]; // The set of galleries associated with the group
}
```

- [x] Define Firestore security rules to limit access to class data to the teachers in the list and students in the list.
- [x] Create a teacher account request form
- [x] Add teacher flag as claim in accounts
- [x] Add a top page "Teach" link to the landing page 
- [x] `/class/`: View and navigate classes
  - [x] If not authenticated, indicate that one must be logged into view and create classes
  - [x] If not a teacher, indicate that one must be given permission to create and view classes
  - [x] Explain the concept of classes
  - [x] Provide a link to create a new group
  - [x] Show all groups created, each linked to `/class/id`
- [x] `/class/new`: create a group of students
  - [x] If not authenticated, indicate that one must be logged into create classes
  - [x] If not a teacher account, indicate that one must be an approved teacher to create a class
  - [x] A form that includes 
    - [x] Name
    - [x] Description
    - [x] Textbox for CSV student information. 
      - [x] The CSV information is automatically parsed, rendering what will be produced
      - [x] The usernames produced are of the format `[meta1][meta2]...[meta-n]-[groupname]`, where each meta is the first 3 characters of each metadata provided, and the `groupname` is the lowercase, space removed group name.
      - [x] The form generates usernames and passwords live, so the teacher can see what they will be before submission. Generated usernames and passwords can be edited to the teachers' liking, for recognizability.
      - [x] Enforce no more than 50 in any one batch (100 accounts/hour limit imposed by Firebase Auth).
    - [x] Form warns the teacher that they will get a download upon submission and need to save all the passwords since they will not be recoverable.
    - [x] Upon submission:
      - [x] Form is deactivated to prevent further editing and loading feedback is given
      - [x] Form submission calls a cloud function `createGroup()` that uses admin SDK to bulk create accounts and return the list of username and passwords generated.
      - [x] Upon success, the form is hidden and the data is assembled as a CSV and automatically downloaded to the teachers' machine for safe storage, with an indicator of success and a recommendation of where to store the information.
      - [x] Upon failure, information is given to troubleshoot the root cause of the failure.
      - [x] A button is revealed that asks the teacher to confirm they have securely stored the student authentication information, and when pressed, it takes them to the newly created class page `/class/[id]`
- [x] `/class/[id]/`
  - [x] If a teacher or student of the class
    - [x] Shows all learners and their information
    - [x] Shows all previews of all galleries associated with the class
  - [x] If a teacher of the class
    - [x] Allows further bulk creation of accounts per the same flow above, but also adds new learners as creators to associated galleries
    - [x] Allows removal of students from the class, which removes students as creators of associated galleries
    - [x] Allows creation of new galleries associated with the class with all teachers as curator and students as creators
    - [x] Allows addition of teachers, which adds teachers to all galleries of the class
    - [x] Allows removal of teachers, which removes teachers from all galleries of the class
   - [x] If anyone else, indicates that the class is private
- [x] `/gallery/[id]`: If associated with a class, the class name is indicated above the list of curators.
- [x] `/profile`: If a teacher, add the teach link next to the project link
- [x] Generate locale text

**Comment by anushkamalpani** [comment]
@amyjko I am interested in working on this issue

**Comment by anushkamalpani** [comment]
I have been thinking of this idea:
<img width="599" alt="image" src="https://github.com/user-attachments/assets/347e2ba4-5417-46ca-9100-23e38a9291fc">

<img width="471" alt="image" src="https://github.com/user-attachments/assets/4c4a1b33-70e1-432c-8f4c-60e9f2b815d4">
<img width="500" alt="image" src="https://github.com/user-attachments/assets/5f2e40f8-e52f-4471-af3b-24718a0bbb2d">
<img width="415" alt="image" src="https://github.com/user-attachments/assets/5e385605-8abf-43b3-9a85-c9f78e375937">
<img width="420" alt="image" src="https://github.com/user-attachments/assets/55678479-5413-4eac-8311-3047ff53a989">
<img width="423" alt="image" src="https://github.com/user-attachments/assets/367c4c91-2f76-4d13-b3af-d2bdebcaa82a">
<img width="422" alt="image" src="https://github.com/user-attachments/assets/fe556689-0901-467e-9a53-7305037eb8c7">

Sorry this turned out to be way longer than I anticipated

**Comment by amyjko** [comment]
A few comments:

* We can't gather personally identifiable information (PII) from students younger than 13. No first name, no last name, no date of birth, no email address, no phone number, no profile photos. If we do without parent permission, we're violating the U.S. COPA regulation.
* What does "submitted to the teacher" mean?

Process feedback:

* Don't upload text in images; contributors who cannot see images cannot read the text inside the image.
* When you include design proposals, please describe what is happening in each mockup, both for contributors who are not able to see images, but also to help clarify what is happening in the design sketches.

**Comment by amyjko** [comment]
Since there hasn't been any progress on this, and the issue is crucial for our next milestone, I'm going to finish this issue.
