### ISSUE TITLE
Editable animation speed in the toolbar

### ISSUE THREAD

**Issue by amyjko** [wordplaydev/wordplay#522]
### What are you trying to do that you can't?

The animation speed is currently only editable in the settings, but it's often helpful to edit it in the output window too. The current indicator is read only.

### What is your idea?

Extract a component and reuse it in the output toolbar.

**Comment by enricopratama** [comment]
@amyjko may I be assigned into this issue? I feel like I am pretty confident in front end and would like to work on this issue. May I know how I can get started on this?

**Comment by amyjko** [comment]
It's yours! The key places to look:

* `AnimationFactorSetting.ts` (the state that's persisted to control the speed)
* `Settings.svelte` (where animation speed is currently set)
* The `<svelte:fragment slot="extra">` line in `ProjectView.svelte`, where extra controls are added to the `OutputView`. That's where we would put the animation speed setting, like the one in `Settings.svelte`

**Comment by enricopratama** [comment]
Hi Amy! Here is the pull request for this issue:
https://github.com/wordplaydev/wordplay/pull/588 
Excited for any feedback, sorry this took so long for me to do, had trouble with Svelte. Will up my pace for future issues! 🙏

**Comment by amyjko** [comment]
Thanks! I will review soon, likely Saturday.
