### ISSUE TITLE
Pressing `Enter` visually skips line following a language tag

### ISSUE THREAD

**Issue by azmec** [wordplaydev/wordplay#523]
### What happened?

Pressing `Enter` to create a newline following a line with a language tag visually skips the newly created line to the line following it, if it exists. Logically, the caret is on the newly created line, but it visually appears to be at the start of the line following it.

1. Copy and paste the following code into a Wordplay performance.
    ```
   text: "foo"/en"bar"/es
   number: 1
    ```
3. Ensure the "Localize code when available" option is enabled.
2. Move the cursor to the end of Line 1.
3. Press `Enter`.
4. Observe that there is a new, blank line between the lines containing `foo` and `number`, but the cursor sits at the beginning of Line 3 instead of Line 2.
5. Type anything. Observe that the cursor jumps to Line 2 as you type.

### Anything else?

Below is a video of the bug.

https://github.com/user-attachments/assets/deab5809-59a7-4f1b-888f-b942330d3375

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Linux

**Comment by azmec** [comment]
Additionally defect behavior that may be related:

Attempting to type in an empty line following a language tag will enter text in the line above the empty line.

1. Copy and paste the following code into a Wordplay performance, including the whitespace.
    ```
    text: "foo"/en"bar"/es


    number: 1
    ```
3. Ensure the "Localize code when available" option is enabled.
2. Attempt to click on Line 3 to move the cursor to Line 3. Observe that the cursor is instead moved to Line 4.
3. Move the cursor to Line 3.
4. Attempt to type anything.
5. Observe that the cursor jumped to Line 2 and what you typed appears on Line 2.

Below is a video of the described behavior.

https://github.com/user-attachments/assets/bde2dadf-859a-4627-ae4b-1c7b46249ef6

**Comment by amyjko** [comment]
Thanks, these are both related! There's a bug somewhere in the cursor location computation that isn't accounting for hidden tokens.
