### ISSUE TITLE
"Remove" button for Gallery does not work

### ISSUE THREAD

**Issue by azmec** [wordplaydev/wordplay#525]
### What happened?

When in a gallery you are a curator of, you have the option to remove projects from the gallery. However, pressing the associated "remove" button does not remove the project from the gallery.

1. Enter a gallery you are a curator of. Ensure it has a project you can remove.
2. For a project, click the "⨉" button to bring up the option to remove the project.
3. Click "remove".
4. Observe the project remains in the gallery.
5. Refresh the page for good measure. Observe the project is still in the gallery.

### Anything else?

Below is a video of the defect.

https://github.com/user-attachments/assets/87c36c73-8a46-45f2-8a38-809fca0efca0

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

Linux

**Comment by amyjko** [comment]
Blah, NoSQL denormalization strikes again. (The gallery has the project, but the project doessn't list the gallery, which means a guard is preventing it from being removed).

**Comment by amyjko** [comment]
Resolved by 9399ae7ced6105dc70b493a5e9586d048f585fdb.
