### ISSUE TITLE
Highlight Over Adding Project Misaligned 

### ISSUE THREAD

**Issue by joonpiter** [wordplaydev/wordplay#530]
### What happened?

When hovering over "new project," the highlighting feature seems to be misaligned with the actual highlight of the symbol  
<img width="491" alt="Screen Shot 2024-07-16 at 4 10 05 PM" src="https://github.com/user-attachments/assets/c45d5338-c470-4bff-860b-505be9b9efa7">

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

macOS

**Comment by amyjko** [comment]
This was resolved by a fix last week.
