### ISSUE TITLE
Scene and act specific links to tutorial don't stay at target scene or act

### ISSUE THREAD

**Issue by azmec** [wordplaydev/wordplay#533]
### What happened?

The Guide often links to specific act or scene in the tutorial to supplement documentation. When the user follows these links, the expected behavior is to be brought to the relevant act and scene in the tutorial and to remain there. Instead, the user is brought to the relevant act and scene, but the act and scene quickly change to the last act and scene the user visited in the tutorial.

1. Ensure you are logged into a Wordplay account.
1. Open the Wordplay tutorial.
2. Open any scene from the dropdown to the right of "Learn".
3. Follow the "Projects" link in the bottom-left.
4. Follow the "Guide" link in the bottom-left.
5. Follow the link to the "Number" documentation.
6. Follow the "learn more" link in the documentation.
7. Observe that you are briefly brought to the "Numbers" scene but quickly brought to the scene you visited in Step 2.

This behavior is not reproduced when the user is logged out or in a private/incognito window.

### Anything else?

Below is a recording of the observed defect.

https://github.com/user-attachments/assets/c8a20f51-3344-44db-8e20-960cbc79051a

### What browsers are you seeing the problem on?

Firefox, Chrome

### What operating system are you using?

Linux

**Comment by amyjko** [comment]
Thanks, reproduced! I'll tackle this one.
