### ISSUE TITLE
Differentiate tutorial interface highlights by color

### ISSUE THREAD

**Issue by amyjko** [wordplaydev/wordplay#535]
### What are you trying to do that you can't?

When there are two or more tutorial highlights of an interface element, they are both yellow, making it hard to know which element is being referred to.

### What is your idea?

Use multiple colors to distinguish them. Just make a list of standard UI colors already defined in Wordplay, and work through the list to define distinct highlight colors.

**Comment by SathvikCookie** [comment]
@amyjko Hey, how should I get started on this?

**Comment by amyjko** [comment]
@SathvikCookie It sounds like you'd like be to assigned? (I'll assume and assign you). (Remember, our workflow is that you request assignment if you want to work on something).

The key places to work on this are:

* `TutorialHighlight.svelte`
* `TutorialView.svelte`
* `ConceptLinkUI.svelte`
* `Documentation.svelte`

Those are all of the places that render tutorial highlights that need to be differentiated.

One challenge with this one is choosing colors: they should use the theme color CSS variables defined in `app.html`, but they also shouldn't collide too much with the meanings of different colors. It's possible that shapes might be better than colors, for example, or numbers even.

**Comment by SathvikCookie** [comment]
<img width="515" alt="Screenshot 2024-10-25 at 12 43 40 PM" src="https://github.com/user-attachments/assets/1bf655b8-d504-4a5f-8d3c-dc2d18a099d0">
<img width="515" alt="Screenshot 2024-10-25 at 12 44 06 PM" src="https://github.com/user-attachments/assets/cd1a97d3-e648-4fc3-be73-d2c5cd8f8fd0">

Here is the design I came up with. When there is more than one highlight it displays a number indexed to the corresponding highlight. If there is only 1 highlight the design remains the same as before with no numbers. I think we may have to look into adding contrast to the highlights.

**Comment by amyjko** [comment]
I approve this design, with the one caveat around color contrast. But that can be iterated on in implementation.

**Comment by SathvikCookie** [comment]
![Screenshot 2024-10-28 at 10 46 53 PM](https://github.com/user-attachments/assets/47cd5cd7-d9f6-4cfa-bf84-22b767e4bed7)

Added a black outline to the numbers to help with contrast to make it a little more readable, let me know if this works or if I should look into other options.

**Comment by amyjko** [comment]
I think it would work without the opacity on it. Here are the minimum contrast guidelines:

https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html

Check both dark and light mode.

**Comment by SathvikCookie** [comment]
<img width="579" alt="Screenshot 2024-10-29 at 5 10 44 PM" src="https://github.com/user-attachments/assets/da6f4c2f-54d7-4091-983c-337e311b946f">
<img width="579" alt="Screenshot 2024-10-29 at 5 10 08 PM" src="https://github.com/user-attachments/assets/86604b67-883c-4dad-94c3-b4a55b09f5f8">

I turned off the transparency, and set the text color to black to increase contrast. I believe the new design matches the guidelines, and works with both dark and light mode.
