### ISSUE TITLE
Inconsistent casing in start/stop explanations for nodes

### ISSUE THREAD

**Issue by amyjko** [wordplaydev/wordplay#563]
### What happened?

See `"start"` and `"finish"` fields of the `en-US.json` locale. Some are initial case (e.g., `ExpressionPlaceholder`), others are lower case (e.g., `FunctionDefinition`). They should all be initial upper case.

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What operating system are you using?

macOS

**Comment by markhan0805** [comment]
The fields referred to as 'stop' in the description should be labeled as 'finish' instead.

**Comment by amyjko** [comment]
Thanks, fixed.

**Comment by amyjko** [comment]
Resolved by #581.
