### ISSUE TITLE
Removing Hanja from the Korean/한국어 option in the language menu

### ISSUE THREAD

**Issue by anhourandaquarter** [wordplaydev/wordplay#584]
### What are you trying to do that you can't?

In the language selection menu, the option to select Korean shows both Hangeul and Hanja:

![image](https://github.com/user-attachments/assets/303d1531-1eeb-45d5-b5bc-e187eef6b75f)

I suggest removing the Hanja and only using the Hangeul representation, as it both helps decolonize the language and make Korean distinct from other languages that use Chinese characters.

### What is your idea?

Just remove the 韓國語 from the language selection. : )

**Comment by amyjko** [comment]
Thanks! I went ahead and removed this form `LanguageCode.ts`.
