### ISSUE TITLE
Flaky Playwright Test

### ISSUE THREAD

**Issue by ahsoj22** [wordplaydev/wordplay#597]
### What happened?

**Playwright Test Failed**
   When running playwright tests through Github for issue 595 the tests are timing out.

### Anything else?

Error can be found here:
https://github.com/wordplaydev/wordplay/actions/runs/11849079545/job/33296436750

Tests could be failing due to Github not being able to load necessary items for test in time

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows

**Comment by amyjko** [comment]
Thanks @ahsoj22, saw this again on a different build in GitHub, so it's real. Want to try to fix it?
