### ISSUE TITLE
Unable to type when prompted in 'Learn'

### ISSUE THREAD

**Issue by navyacodes** [wordplaydev/wordplay#615]
### What happened?

I was going through the Learn, in the section 'It's the Little Things' and the subsection 'Text' when I encountered an error on slide 4/19 where I was unable to type any code; there was an empty 'text' (' ') autoloaded into the code editor. 

I was clicking through the slides (but not answering many of the prompts) prior to this. When I double-click in between the apostrophes, I get a pop-up explaining 'this is translation'. I can't click the dropdown associated with translation, either.

When I opened a new tab in my browser to the same slide of the tutorial, it showed the text that I typed. I'm unable to reproduce the behavior again.  

### Anything else?

Here are the errors being shown through inspect > console. 
![image](https://github.com/user-attachments/assets/770d0033-63a5-461b-b99d-78a5aef7e464)

Here is a view of my screen: 
![image](https://github.com/user-attachments/assets/fbefd27d-653d-4ce0-8ab8-3f8a5c924748)

### What browsers are you seeing the problem on?

Chrome

### What operating system are you using?

Windows

**Comment by amyjko** [comment]
Thanks for the bug report @navyacodes, I'll try to track down the cause of this!

**Comment by amyjko** [comment]
I think I found some reproduction steps:

* Open `/learn?locale=en-US&act=2&scene=2&pause=7` in a private browsing tab so there's no persisted versions of the project
* Type; notice that nothing appears in the editor
* Navigate back to a previous step in the tutorial
* Navigate forward to the original step; notice that the text typed has appeared

This likely has something to do with the way the tutorial view is persisting and updating projects with the `ProjectsDatabase`. It's going to take a bit more time to debug, but now we can reproduce.

**Comment by amyjko** [comment]
Found the cause: when the tutorial first checks to see if a version of the project is saved locally or in the cloud, if it was, it was not returning the history object, and so there was no store for the project to notify of edits, hence the lack of feedback in the editor.
